$UVMF_VIP_LIBRARY_HOME/interface_packages/soc_ifc_ctrl_pkg/src/soc_ifc_ctrl_if.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/soc_ifc_ctrl_pkg/src/soc_ifc_ctrl_monitor_bfm.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/soc_ifc_ctrl_pkg/src/soc_ifc_ctrl_driver_bfm.sv
