#!/bin/bash

LD_LIBRARY_PATH=${QUESTA_MVC_HOME}/questa_mvc_core/linux_x86_64_gcc-6.3_ius:${IUS_HOME}/tools/cdsgcc/gcc/6.3/install/lib64:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

xrun -sv -uvm -quiet -access +rwc -64bit -timescale 1ns/1ns \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv \
    ${QUESTA_MVC_HOME}/include/questa_mvc_svapi.sv \
    +define+MAP_PROT_ATTR ${QUESTA_MVC_HOME}/questa_mvc_src/sv/mvc_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/apb3 ${QUESTA_MVC_HOME}/questa_mvc_src/sv/apb3/mgc_apb3_v1_0_pkg.sv \
    +incdir+../config_policies \
    ../config_policies/qvip_apb5_slave_params_pkg.sv \
    qvip_apb5_slave_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/apb3/modules ${QUESTA_MVC_HOME}/questa_mvc_src/sv/apb3/modules/apb5_master.sv \
    default_clk_gen.sv \
    default_reset_gen.sv \
    hdl_qvip_apb5_slave.sv \
    hvl_qvip_apb5_slave.sv \
    -sv_root ${QUESTA_MVC_HOME}/questa_mvc_core/linux_x86_64_gcc-6.3_ius \
    -sv_lib libapb3_IN_SystemVerilog_IUS_full \
    +UVM_TESTNAME=qvip_apb5_slave_test_base \
    +SEQ=qvip_apb5_slave_vseq_base
