$UVMF_VIP_LIBRARY_HOME/interface_packages/fuse_ctrl_lc_otp_if_pkg/src/fuse_ctrl_lc_otp_if_if.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/fuse_ctrl_lc_otp_if_pkg/src/fuse_ctrl_lc_otp_if_monitor_bfm.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/fuse_ctrl_lc_otp_if_pkg/src/fuse_ctrl_lc_otp_if_driver_bfm.sv
