# Copyright (C) Microsoft Corporation. All rights reserved.
schema_version:       1.0.0

expansion:
  vcs:
    description: VCS-only command line expansions
    condition:
      after: --tool
    expand:
      - TIMESCALE_VCS=1ns/1ps
    args:
      - param: vcs
      - param: --analyze-args=-assert svaext
    implied: true
