uvmf:
  environments:
    SHA512:
      agents:
      - initiator_responder: INITIATOR
        name: SHA512_in_agent
        type: SHA512_in
      - initiator_responder: RESPONDER
        name: SHA512_out_agent
        type: SHA512_out
      analysis_components:
      - name: SHA512_pred
        parameters: []
        type: SHA512_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: SHA512_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: SHA512_out_transaction
      subenvs: []
      tlm_connections:
      - driver: SHA512_in_agent.monitored_ap
        receiver: SHA512_pred.SHA512_in_agent_ae
        validate: 'True'
      - driver: SHA512_pred.SHA512_sb_ap
        receiver: SHA512_sb.expected_analysis_export
        validate: 'True'
      - driver: SHA512_out_agent.monitored_ap
        receiver: SHA512_sb.actual_analysis_export
        validate: 'True'
