uvmf:
  environments:
    soc_ifc:
      agents:
      - initiator_responder: INITIATOR
        name: dummy_avery_aaxi_agent
        type: dummy_avery_aaxi
      - initiator_responder: INITIATOR
        name: soc_ifc_ctrl_agent
        type: soc_ifc_ctrl
      - initiator_responder: INITIATOR
        name: cptra_ctrl_agent
        type: cptra_ctrl
      - initiator_responder: INITIATOR
        name: ss_mode_ctrl_agent
        type: ss_mode_ctrl
      - initiator_responder: RESPONDER
        name: soc_ifc_status_agent
        type: soc_ifc_status
      - initiator_responder: RESPONDER
        name: cptra_status_agent
        type: cptra_status
      - initiator_responder: RESPONDER
        name: ss_mode_status_agent
        type: ss_mode_status
      - initiator_responder: RESPONDER
        name: mbox_sram_agent
        type: mbox_sram
      analysis_components:
      - name: soc_ifc_pred
        parameters: []
        type: soc_ifc_predictor
      - name: soc_ifc_sb
        parameters: []
        type: soc_ifc_scoreboard
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: mvc_pkg
      - name: mgc_ahb_v2_0_pkg
      - name: rw_txn_pkg
      non_uvmf_components: []
      parameters: []
      qvip_connections:
      - ap_key: burst_transfer
        driver: qvip_ahb_lite_slave_subenv_ahb_lite_slave_0
        receiver: soc_ifc_pred.ahb_slave_0_ae
        validate: 'false'
      qvip_memory_agents: []
      qvip_subenvs:
      - name: qvip_ahb_lite_slave_subenv
        type: qvip_ahb_lite_slave
      register_model:
        maps:
        - interface: qvip_ahb_lite_slave_subenv.ahb_lite_slave_0
          name: fixme_map
          qvip_agent: 'True'
        reg_block_class: soc_ifc_reg_model_top
        reg_model_package: soc_ifc_reg_model_top_pkg
        use_adapter: 'True'
        use_explicit_prediction: 'True'
      scoreboards: []
      subenvs: []
      tlm_connections:
      - driver: soc_ifc_ctrl_agent.monitored_ap
        receiver: soc_ifc_pred.soc_ifc_ctrl_agent_ae
        validate: 'True'
      - driver: cptra_ctrl_agent.monitored_ap
        receiver: soc_ifc_pred.cptra_ctrl_agent_ae
        validate: 'True'
      - driver: ss_mode_ctrl_agent.monitored_ap
        receiver: soc_ifc_pred.ss_mode_ctrl_agent_ae
        validate: 'True'
      - driver: mbox_sram_agent.monitored_ap
        receiver: soc_ifc_pred.mbox_sram_agent_ae
        validate: 'True'
      - driver: dummy_avery_aaxi_agent.monitored_ap
        receiver: soc_ifc_pred.axi_sub_0_ae
        validate: 'True'
      - driver: soc_ifc_pred.soc_ifc_sb_ap
        receiver: soc_ifc_sb.expected_analysis_export
        validate: 'True'
      - driver: soc_ifc_pred.cptra_sb_ap
        receiver: soc_ifc_sb.expected_cptra_analysis_export
        validate: 'True'
      - driver: soc_ifc_pred.ss_mode_sb_ap
        receiver: soc_ifc_sb.expected_ss_mode_analysis_export
        validate: 'True'
      - driver: soc_ifc_pred.soc_ifc_sb_ahb_ap
        receiver: soc_ifc_sb.expected_ahb_analysis_export
        validate: 'True'
      - driver: soc_ifc_pred.soc_ifc_sb_axi_ap
        receiver: soc_ifc_sb.expected_axi_analysis_export
        validate: 'True'
      - driver: soc_ifc_status_agent.monitored_ap
        receiver: soc_ifc_sb.actual_analysis_export
        validate: 'True'
      - driver: cptra_status_agent.monitored_ap
        receiver: soc_ifc_sb.actual_cptra_analysis_export
        validate: 'True'
      - driver: ss_mode_status_agent.monitored_ap
        receiver: soc_ifc_sb.actual_ss_mode_analysis_export
        validate: 'True'
