uvmf:
  environments:
    caliptra_top:
      imports: []
#      - name: "rw_txn_pkg"

      agents: []

      analysis_components: []
#      - name: caliptra_top_pred
#        type: caliptra_top_predictor
#      - name: caliptra_top_sb
#        type: caliptra_top_scoreboard

#      analysis_exports :
#        - name: "ahb_master_0_export"
#          trans_type: "rw_txn"
#          connected_to: "soc_ifc_pred.ahb_master_0_ae"
#        - name: "apb5_master_0_export"
#          trans_type: "rw_txn"
#          connected_to: "soc_ifc_pred.apb5_master_0_ae"

      analysis_ports: []

      config_constraints: []
      config_vars: []

      parameters: []

      scoreboards: []
#      - name: caliptra_top_sb
#        sb_type: uvmf_in_order_scoreboard
#        trans_type: soc_ifc_status_transaction

      #TODO ADD JTAG, QSPI, UART, I3C agents
      subenvs:
        - { name: "soc_ifc_subenv", type: "soc_ifc" }

      qvip_subenvs : []

      qvip_connections : []

      tlm_connections: []
#      ############# Predictor connections ############
#      - driver: soc_ifc_ctrl_agent.monitored_ap                    # SOC IFC Control
#        receiver: soc_ifc_pred.soc_ifc_ctrl_agent_ae               #
#      - driver: cptra_ctrl_agent.monitored_ap                      # Caliptra Control
#        receiver: soc_ifc_pred.cptra_ctrl_agent_ae                 #
##      - driver: qvip_ahb_lite_master_subenv.ahb_master_0.export_rw # AHB
##        receiver: soc_ifc_pred.ahb_master_0_ae                     #
##      - driver: qvip_apb5_master_subenv.apb5_master_0.export_rw    # APB
##        receiver: soc_ifc_pred.apb5_master_0_ae                    #
#      ############# Scoreboard connections ############
#      # Expected
#      - driver: soc_ifc_pred.soc_ifc_sb_ap                  #
#        receiver: soc_ifc_sb.expected_analysis_export       #
#      - driver: soc_ifc_pred.cptra_sb_ap                    #
#        receiver: soc_ifc_sb.expected_cptra_analysis_export #
#      - driver: soc_ifc_pred.soc_ifc_sb_ahb_ap              #
#        receiver: soc_ifc_sb.expected_ahb_analysis_export   #
#      - driver: soc_ifc_pred.soc_ifc_sb_apb_ap              #
#        receiver: soc_ifc_sb.expected_apb_analysis_export   #
#      # Actual
#      - driver: soc_ifc_status_agent.monitored_ap         #
#        receiver: soc_ifc_sb.actual_analysis_export       #
#      - driver: cptra_status_agent.monitored_ap           #
#        receiver: soc_ifc_sb.actual_cptra_analysis_export #
##      - driver: 'qvip_ahb_lite_slave_subenv_ahb_lite_slave_0_ap["burst_transfer_sb"]' #
##        receiver: soc_ifc_sb.actual_ahb_analysis_export                               #
##      - driver: 'qvip_apb5_slave_subenv_apb5_master_0_ap["trans_ap_sb"]'              #
##        receiver: soc_ifc_sb.actual_apb_analysis_export                               #

#      register_model: []
#        use_adapter: "True"
#        use_explicit_prediction: "True"
#        reg_block_class: soc_ifc_reg_model_top
#        reg_model_package: soc_ifc_reg_model_top_pkg
#        maps:
#          - name: "fixme_map"
#            interface: "qvip_ahb_lite_slave_subenv.ahb_lite_slave_0"
#            qvip_agent: "True"
