
// This file was autogenerated by PeakRDL-uvm
package sha512_reg_uvm;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // Reg - sha512_reg::SHA512_NAME
    class sha512_reg__SHA512_NAME extends uvm_reg;
        rand uvm_reg_field NAME;

        function new(string name = "sha512_reg__SHA512_NAME");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.NAME = new("NAME");
            this.NAME.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : sha512_reg__SHA512_NAME

    // Reg - sha512_reg::SHA512_VERSION
    class sha512_reg__SHA512_VERSION extends uvm_reg;
        rand uvm_reg_field VERSION;

        function new(string name = "sha512_reg__SHA512_VERSION");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.VERSION = new("VERSION");
            this.VERSION.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
        endfunction : build
    endclass : sha512_reg__SHA512_VERSION

    // Reg - sha512_reg::SHA512_CTRL
    class sha512_reg__SHA512_CTRL extends uvm_reg;
        rand uvm_reg_field INIT;
        rand uvm_reg_field NEXT;
        rand uvm_reg_field MODE;

        function new(string name = "sha512_reg__SHA512_CTRL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.INIT = new("INIT");
            this.INIT.configure(this, 1, 0, "WO", 1, 'h0, 1, 1, 0);
            this.NEXT = new("NEXT");
            this.NEXT.configure(this, 1, 1, "WO", 1, 'h0, 1, 1, 0);
            this.MODE = new("MODE");
            this.MODE.configure(this, 2, 2, "WO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : sha512_reg__SHA512_CTRL

    // Reg - sha512_reg::SHA512_STATUS
    class sha512_reg__SHA512_STATUS extends uvm_reg;
        rand uvm_reg_field READY;
        rand uvm_reg_field VALID;

        function new(string name = "sha512_reg__SHA512_STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.READY = new("READY");
            this.READY.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.VALID = new("VALID");
            this.VALID.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : sha512_reg__SHA512_STATUS

    // Reg - sha512_reg::SHA512_BLOCK
    class sha512_reg__SHA512_BLOCK extends uvm_reg;
        rand uvm_reg_field BLOCK;

        function new(string name = "sha512_reg__SHA512_BLOCK");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.BLOCK = new("BLOCK");
            this.BLOCK.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : sha512_reg__SHA512_BLOCK

    // Reg - sha512_reg::SHA512_DIGEST
    class sha512_reg__SHA512_DIGEST extends uvm_reg;
        rand uvm_reg_field DIGEST;

        function new(string name = "sha512_reg__SHA512_DIGEST");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.DIGEST = new("DIGEST");
            this.DIGEST.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : sha512_reg__SHA512_DIGEST

    // Addrmap - sha512_reg
    class sha512_reg extends uvm_reg_block;
        rand sha512_reg__SHA512_NAME SHA512_NAME[2];
        rand sha512_reg__SHA512_VERSION SHA512_VERSION[2];
        rand sha512_reg__SHA512_CTRL SHA512_CTRL;
        rand sha512_reg__SHA512_STATUS SHA512_STATUS;
        rand sha512_reg__SHA512_BLOCK SHA512_BLOCK[32];
        rand sha512_reg__SHA512_DIGEST SHA512_DIGEST[16];

        function new(string name = "sha512_reg");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            foreach(this.SHA512_NAME[i0]) begin
                this.SHA512_NAME[i0] = new($sformatf("SHA512_NAME[%0d]", i0));
                this.SHA512_NAME[i0].configure(this);
                
                this.SHA512_NAME[i0].build();
                this.default_map.add_reg(this.SHA512_NAME[i0], 'h0 + i0*'h4);
            end
            foreach(this.SHA512_VERSION[i0]) begin
                this.SHA512_VERSION[i0] = new($sformatf("SHA512_VERSION[%0d]", i0));
                this.SHA512_VERSION[i0].configure(this);
                
                this.SHA512_VERSION[i0].build();
                this.default_map.add_reg(this.SHA512_VERSION[i0], 'h8 + i0*'h4);
            end
            this.SHA512_CTRL = new("SHA512_CTRL");
            this.SHA512_CTRL.configure(this);

            this.SHA512_CTRL.build();
            this.default_map.add_reg(this.SHA512_CTRL, 'h10);
            this.SHA512_STATUS = new("SHA512_STATUS");
            this.SHA512_STATUS.configure(this);

            this.SHA512_STATUS.build();
            this.default_map.add_reg(this.SHA512_STATUS, 'h18);
            foreach(this.SHA512_BLOCK[i0]) begin
                this.SHA512_BLOCK[i0] = new($sformatf("SHA512_BLOCK[%0d]", i0));
                this.SHA512_BLOCK[i0].configure(this);
                
                this.SHA512_BLOCK[i0].build();
                this.default_map.add_reg(this.SHA512_BLOCK[i0], 'h80 + i0*'h4);
            end
            foreach(this.SHA512_DIGEST[i0]) begin
                this.SHA512_DIGEST[i0] = new($sformatf("SHA512_DIGEST[%0d]", i0));
                this.SHA512_DIGEST[i0].configure(this);
                
                this.SHA512_DIGEST[i0].build();
                this.default_map.add_reg(this.SHA512_DIGEST[i0], 'h100 + i0*'h4);
            end
        endfunction : build
    endclass : sha512_reg

endpackage: sha512_reg_uvm
