// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef SHA512_INTR_REGS_HEADER
#define SHA512_INTR_REGS_HEADER


#define SHA512_INTR_REGS_INTR_BLOCK_RF_GLOBAL_INTR_EN_R                         (0x0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_GLOBAL_INTR_EN_R_ERROR_EN_LOW            (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_GLOBAL_INTR_EN_R_ERROR_EN_MASK           (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_GLOBAL_INTR_EN_R_NOTIF_EN_LOW            (1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_GLOBAL_INTR_EN_R_NOTIF_EN_MASK           (0x2)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_EN_R                          (0x4)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_EN_R_ERROR0_EN_LOW            (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_EN_R_ERROR0_EN_MASK           (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_EN_R_ERROR1_EN_LOW            (1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_EN_R_ERROR1_EN_MASK           (0x2)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_EN_R_ERROR2_EN_LOW            (2)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_EN_R_ERROR2_EN_MASK           (0x4)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_EN_R_ERROR3_EN_LOW            (3)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_EN_R_ERROR3_EN_MASK           (0x8)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_INTR_EN_R                          (0x8)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_INTR_EN_R_NOTIF_CMD_DONE_EN_LOW    (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_INTR_EN_R_NOTIF_CMD_DONE_EN_MASK   (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_GLOBAL_INTR_R                      (0xc)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_GLOBAL_INTR_R_AGG_STS_LOW          (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_GLOBAL_INTR_R_AGG_STS_MASK         (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_GLOBAL_INTR_R                      (0x10)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_GLOBAL_INTR_R_AGG_STS_LOW          (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_GLOBAL_INTR_R_AGG_STS_MASK         (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTERNAL_INTR_R                    (0x14)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTERNAL_INTR_R_ERROR0_STS_LOW     (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTERNAL_INTR_R_ERROR0_STS_MASK    (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTERNAL_INTR_R_ERROR1_STS_LOW     (1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTERNAL_INTR_R_ERROR1_STS_MASK    (0x2)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTERNAL_INTR_R_ERROR2_STS_LOW     (2)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTERNAL_INTR_R_ERROR2_STS_MASK    (0x4)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTERNAL_INTR_R_ERROR3_STS_LOW     (3)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTERNAL_INTR_R_ERROR3_STS_MASK    (0x8)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_INTERNAL_INTR_R                    (0x18)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_INTERNAL_INTR_R_NOTIF_CMD_DONE_STS_LOW                                                                             (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_INTERNAL_INTR_R_NOTIF_CMD_DONE_STS_MASK                                                                            (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_TRIG_R                        (0x1c)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_TRIG_R_ERROR0_TRIG_LOW        (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_TRIG_R_ERROR0_TRIG_MASK       (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_TRIG_R_ERROR1_TRIG_LOW        (1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_TRIG_R_ERROR1_TRIG_MASK       (0x2)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_TRIG_R_ERROR2_TRIG_LOW        (2)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_TRIG_R_ERROR2_TRIG_MASK       (0x4)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_TRIG_R_ERROR3_TRIG_LOW        (3)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR_INTR_TRIG_R_ERROR3_TRIG_MASK       (0x8)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_INTR_TRIG_R                        (0x20)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_INTR_TRIG_R_NOTIF_CMD_DONE_TRIG_LOW                                                                                (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_INTR_TRIG_R_NOTIF_CMD_DONE_TRIG_MASK                                                                               (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR0_INTR_COUNT_R                      (0x100)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR1_INTR_COUNT_R                      (0x104)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR2_INTR_COUNT_R                      (0x108)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR3_INTR_COUNT_R                      (0x10c)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_CMD_DONE_INTR_COUNT_R              (0x180)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR0_INTR_COUNT_INCR_R                 (0x200)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR0_INTR_COUNT_INCR_R_PULSE_LOW       (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR0_INTR_COUNT_INCR_R_PULSE_MASK      (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR1_INTR_COUNT_INCR_R                 (0x204)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR1_INTR_COUNT_INCR_R_PULSE_LOW       (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR1_INTR_COUNT_INCR_R_PULSE_MASK      (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR2_INTR_COUNT_INCR_R                 (0x208)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR2_INTR_COUNT_INCR_R_PULSE_LOW       (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR2_INTR_COUNT_INCR_R_PULSE_MASK      (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR3_INTR_COUNT_INCR_R                 (0x20c)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR3_INTR_COUNT_INCR_R_PULSE_LOW       (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_ERROR3_INTR_COUNT_INCR_R_PULSE_MASK      (0x1)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_CMD_DONE_INTR_COUNT_INCR_R         (0x210)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_CMD_DONE_INTR_COUNT_INCR_R_PULSE_LOW                                                                               (0)
#define SHA512_INTR_REGS_INTR_BLOCK_RF_NOTIF_CMD_DONE_INTR_COUNT_INCR_R_PULSE_MASK                                                                              (0x1)


#endif