---
provides: [aes_param_pkg]
schema_version: 2.4.0
requires: []
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files: 
      - $COMPILE_ROOT/rtl/aes_param_pkg.sv
---
provides: [aes_ctrl]
schema_version: 2.4.0
requires:
  - libs
  - keyvault
  - aes_param_pkg
  - kv_defines_pkg
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/aes_intr_regs_pkg.sv
      - $COMPILE_ROOT/rtl/aes_ctrl.sv
      - $COMPILE_ROOT/rtl/aes.v
      #- $COMPILE_ROOT/rtl/aes_param.sv
      - $COMPILE_ROOT/rtl/aes_core.v
      - $COMPILE_ROOT/rtl/aes_decipher_block.v
      - $COMPILE_ROOT/rtl/aes_encipher_block.v
      - $COMPILE_ROOT/rtl/aes_inv_sbox.v
      - $COMPILE_ROOT/rtl/aes_key_mem.v
      - $COMPILE_ROOT/rtl/aes_sbox.v
      - $COMPILE_ROOT/rtl/aes_cbc.sv
      - $COMPILE_ROOT/rtl/aes_core_cbc.v
      - $COMPILE_ROOT/rtl/aes_intr_regs.sv
    tops: [aes_ctrl]
  rtl_lint:
    directories: []
    waiver_files:
      - $COMPILE_ROOT/config/design_lint/aes_ctrl/sglint_waivers
    black_box:
      - aes_intr_regs
---
provides: [aes_cbc_tb]  
schema_version: 2.4.0
requires: 
  - aes_ctrl
targets:
  tb:
    directories: 
      - $COMPILE_ROOT/tb
    files:
      - $COMPILE_ROOT/tb/aes_cbc_tb.sv
    tops: [aes_cbc_tb]
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - +define+CLP_ASSERT_ON
        #- '-v2k_generate'
        #- '-timescale=1ns/1ps'
        - '-noinherit_timescale=1ns/1ps'
        #- '-ucli -i dump.ucli'
      #sim:
        #- '-ucli -i dump.ucli'
