---
provides: [sha512_ctrl]
schema_version: 2.4.0
requires:
  - libs
  - keyvault
  - pcrvault
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/sha512_reg_pkg.sv
      - $COMPILE_ROOT/rtl/sha512_ctrl.sv
      - $COMPILE_ROOT/rtl/sha512.sv
      - $COMPILE_ROOT/rtl/sha512_param.sv
      - $COMPILE_ROOT/rtl/sha512_core.v
      - $COMPILE_ROOT/rtl/sha512_h_constants.v
      - $COMPILE_ROOT/rtl/sha512_k_constants.v
      - $COMPILE_ROOT/rtl/sha512_w_mem.v
      - $COMPILE_ROOT/rtl/sha512_reg.sv
    tops: [sha512_ctrl]
  rtl_lint:
    directories: []
    waiver_files: 
      #- $COMPILE_ROOT/config/rtl_lint/sha512.waiver
      - $COMPILE_ROOT/config/design_lint/sha512_ctrl/sglint_waivers
    black_box:
      - sha512_reg
---
provides: [sha512_ctrl_32bit_tb]  
schema_version: 2.4.0
requires: 
  - sha512_ctrl
targets:
  tb:
    directories: 
      - $COMPILE_ROOT/tb
    files:
      - $COMPILE_ROOT/tb/sha512_ctrl_32bit_tb.sv
    tops: [sha512_ctrl_32bit_tb]
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - +define+CLP_ASSERT_ON
        #- '-v2k_generate'
        #- '-timescale=1ns/1ps'
        - '-noinherit_timescale=1ns/1ps'
        #- '-ucli -i dump.ucli'
      #sim:
        #- '-ucli -i dump.ucli'
