# Copyright (C) Microsoft Corporation. All rights reserved.

# Go here for details on compile.yml syntax:
# https://dev.azure.com/ms-tsd/Ether/_git/sim-tools?path=%2FSourceFileSpec.docx&version=GBmaster

---
provides: [sha512_ctrl]
schema_version: 2.4.0
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/sha512_ctrl.sv
      - $COMPILE_ROOT/rtl/sha512.v
      - $COMPILE_ROOT/rtl/sha512_param.sv
      - $COMPILE_ROOT/rtl/sha512_core.v
      - $COMPILE_ROOT/rtl/sha512_h_constants.v
      - $COMPILE_ROOT/rtl/sha512_k_constants.v
      - $COMPILE_ROOT/rtl/sha512_w_mem.v
    tops: [sha512_ctrl]
---
provides: [sha512_ctrl_32bit_tb]  
schema_version: 2.4.0
requires: 
  - sha512_ctrl
targets:
  tb:
    directories: 
      - $COMPILE_ROOT/tb
    files:
      - $COMPILE_ROOT/tb/sha512_ctrl_32bit_tb.sv
    tops: [sha512_ctrl_32bit_tb]
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - '-v2k_generate'
        - '-timescale=1ns/1ps'
        - '-noinherit_timescale=1ns/1ps'
        - '-ucli -i dump.ucli'
      sim:
        - '-ucli -i dump.ucli'
