$UVMF_VIP_LIBRARY_HOME/interface_packages/prim_axi_write_if_pkg/src/prim_axi_write_if_if.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/prim_axi_write_if_pkg/src/prim_axi_write_if_monitor_bfm.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/prim_axi_write_if_pkg/src/prim_axi_write_if_driver_bfm.sv
