uvmf:
  environments:
    HMAC:
    
      agents:
      - name: HMAC_in_agent
        type: HMAC_in
        initiator_responder: "INITIATOR"
      - name: HMAC_out_agent
        type: HMAC_out
        initiator_responder: "RESPONDER"
    
      analysis_components:
      - name: HMAC_pred
        type: HMAC_predictor
      analysis_exports: []
      analysis_ports: []
    
      config_constraints: []
      config_vars: []
    
      parameters: []
    
      scoreboards:
      - name: HMAC_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: HMAC_out_transaction
    
      subenvs: []
    
      tlm_connections:
      - driver: HMAC_in_agent.monitored_ap            # connection 00
        receiver: HMAC_pred.HMAC_in_agent_ae
      - driver: HMAC_pred.HMAC_sb_ap                   # connection 01
        receiver: HMAC_sb.expected_analysis_export
      - driver: HMAC_out_agent.monitored_ap           # connection 02
        receiver: HMAC_sb.actual_analysis_export

