# Copyright (C) Microsoft Corporation. All rights reserved.

resources:
  repositories:
    - repository: templates
      type: git
      name: Ether/pipelines

variables:
  - group: AHA_POC_Pipelines
  - name: progress_web
    value: true

  - name: pipeline.start_time
    value: $[format('{0:yyyyMMddHH}', pipeline.startTime)]

  - name: SUBMIT_SMALL_NC_JOBS
    value: submit -i --memory=60

  - name: skip_db_upload_arg
    ${{ if eq(parameters.skip_db_update, 'true') }}:
      value : '--skip_publish'
    ${{ if ne(parameters.skip_db_update, 'true') }}:
      value : ''

parameters:
  - name: skip_db_update
    displayName: Skip merged coverage summary upload to Kusto
    type: boolean
    default: false

  - name: cov_dut_list
    displayName: List of duts that are being processed
    type: object
    default:
    #Random pipeline
      - caliptra_top_tb
      - uvmf_ecc
      - uvmf_pv
      - uvmf_sha512
      - uvmf_hmac
      - uvmf_soc_ifc
      - uvmf_kv
      - uvmf_caliptra_top
    #Directed pipeline
      - sha256_ctrl_tb
      - hmac_ctrl_tb
      - doe_core_cbc_tb
      - sha512_ctrl_32bit_tb
      - ecc_top_tb
      - uvmf_caliptra_top_itrng


stages:
- template: etc/pipelines/templates/promote-pipeline-template.yml@templates
  parameters:
    project: 'AHA_POC'
    repo_url: 'git@ssh.dev.azure.com:v3/ms-tsd/AHA_POC/Caliptra'
    target_branch: 'master'
    top_repo: ''
    post_test_on_fail: true

    additional_test_steps:
    - ${{ each cov_dut in parameters.cov_dut_list }}:
      - ${{ cov_dut }}:
        - enabled: true
        - display_name: Coverage merge for ${{ cov_dut }}
        - commands:
          - $(SUBMIT_SMALL_NC_JOBS) python3w -r requirements.txt \${VERIF_TOOLS}/coverage_merge/coverage_merge.py -f \${CALIPTRA_ROOT}/coverage/config/${{ cov_dut }}.yml $(skip_db_upload_arg)
        - timeout: 30
        - run_in_workspace: true

    post_test_steps:
      - script: |
          source /home/continuous_integration/release/enviro/etc/enviro_startup.bash
          module load settings/tsd/pipelines/frontend
          module load tools/python/python3/3.9.2
          export PYREQUIREMENTS="$(workspace_root)/pipelines/require-progress.txt"
          PROGRESS_CONFIG="$(workspace_root)/progress/config.json"

          enter-workspace tmp_ws "$(SUBMIT_SMALL_NC_JOBS) python3w -r requirements.txt \${VERIF_TOOLS}/coverage_merge/coverage_merge.py -f \${CALIPTRA_ROOT}/coverage/config/caliptra_merge_bench_cov_cfg.yml $(skip_db_upload_arg)"
          cd /home/pure_scratch/caliptra/coverage/integration_lib/3949/caliptra_merge_bench_cov_cfg/
          ln -sfT `ls -rt | tail -n1` latest

        displayName: Coverage merge for all duts
        timeoutInMinutes: 60
        enabled: true
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)



    
