# Copyright (C) Microsoft Corporation. All rights reserved.

trigger: none
pr: none
schedules:
  - cron: '0 8 * * *'
    displayName: Nightly Random Regression
    branches:
      include:
        - master
    always: true

# Point to another repository for the pipeline template
resources:
  repositories:
  - repository: templates
    type: git
    name: Ether/pipelines

variables:
- group: AHA_POC_Pipelines

- name: pipeline.start_time
  value: $[format('{0:yyyyMMddHH}', pipeline.startTime)]

- name: coverage_dir_path
  value: $[format('/home/scratch/caliptra/coverage/{{namespace}}/{0}/{{provider}}/{{tag}}_{1}_{2:yyyyMMddHH}', variables['System.DefinitionId'], variables['Build.BuildId'], pipeline.startTime)]

- name: coverage_root_args
  ${{ if or(eq(parameters.force_global_coverage, 'true'), eq(variables['Build.SourceBranchName'], 'master')) }}:
    value : --coverage-root $COVERAGE_DIR_PATH

- name: PROJECT_SUFFIX
  value: nightly

parameters:
  - name: force_global_coverage
    displayName: Force global coverage collection when running from non-master branch (not recommended)
    type: boolean
    default: false

stages:
  - template: /etc/pipelines/templates/nightly-pipeline-template.yml@templates # Template reference
    parameters:
      project: 'AHA_POC'
      repo_url: 'git@ssh.dev.azure.com:v3/ms-tsd/AHA_POC/Caliptra'
      target_branch: 'master'
      enable_pipeline_audits: True
      legal_header: false
      legal_header_warning: false
      #fixme_args: --exclude-dirs *SCA*

      pre_steps:
        setup: []
        build: []
        test: []
        regress: []

      # Define UVMF playbook invocations
      build_and_sim_map:
# TODO: Add this back once aes uvmf project is fixed
#        - uvmf_aes:
#          - display_name: 'UVMF_AES'
#          - enabled: true
#          - configspec_name: 'integration_lib'
#          - dut: 'uvmf_cbc_AllKAT'
#          - args: ''
#          - testsuites:
#            - l1_regress:
#              - enabled: true
#              - configspec_name: 'integration_lib'
#              - dut: 'uvmf_cbc_AllKAT'
#              - path: 'Caliptra/src/aes/stimulus/L1_regression.yml'
#              - timeout: 15
        - uvmf_ecc:
          - display_name: 'UVMF_ECC'
          - enabled: true
          - configspec_name: 'integration_lib'
          - dut: 'uvmf_ecc'
          - args: '+COVERAGE +CM_HIER=${WORKSPACE}/Caliptra/src/ecc/uvmf_ecc/coverage/config/uvmf_ecc_cm_hier.cfg --submit-resource-args RAM/28000'
          - testsuites:
            - l1_regress:
              - enabled: true
              - configspec_name: 'integration_lib'
              - dut: 'uvmf_ecc'
              - sim_args: '+COVERAGE ${{ variables.coverage_root_args }}'
              - path: '${WORKSPACE}/Caliptra/src/ecc/stimulus/testsuites/ecc_nightly_random_regression.yml'
              - timeout: 1440
        - uvmf_hmac:
          - display_name: 'UVMF_HMAC'
          - enabled: true
          - configspec_name: 'integration_lib'
          - dut: 'uvmf_hmac'
          - args: '+COVERAGE +CM_HIER=${WORKSPACE}/Caliptra/src/hmac/uvmf_2022/coverage/config/uvmf_hmac_cm_hier.cfg --submit-resource-args RAM/28000'
          - testsuites:
            - l1_regress:
              - enabled: true
              - configspec_name: 'integration_lib'
              - dut: 'uvmf_hmac'
              - sim_args: '+COVERAGE ${{ variables.coverage_root_args }}'
              - path: '${WORKSPACE}/Caliptra/src/hmac/stimulus/testsuites/hmac_nightly_random_regression.yml'
              - timeout: 1440

# TODO: Add this back once sha512 uvmf project is fixed
#        - uvmf_sha512:
#          - display_name: 'UVMF_SHA512'
#          - enabled: true
#          - configspec_name: 'integration_lib'
#          - dut: 'uvmf_sha512'
#          - args: ''
#          - testsuites:
#            - l1_regress:
#              - enabled: true
#              - configspec_name: 'integration_lib'
#              - dut: 'uvmf_sha512'
#              - path: 'Caliptra/src/sha512/stimulus/L1_regression.yml'
#              - timeout: 30
        - uvmf_soc_ifc:
            - display_name: 'UVMF_SOC_IFC'
            - enabled: true
            - configspec_name: 'integration_lib'
            - dut: 'uvmf_soc_ifc'
            - args: '+COVERAGE +CM_HIER=${WORKSPACE}/Caliptra/src/soc_ifc/uvmf_soc_ifc/coverage/config/uvmf_soc_ifc_cm_hier.cfg --submit-resource-args RAM/28000'
            - testsuites:
              - l1_regress:
                - enabled: true
                - configspec_name: 'integration_lib'
                - dut: 'uvmf_soc_ifc'
                - sim_args: '+COVERAGE ${{ variables.coverage_root_args }}'
                - path: '${WORKSPACE}/Caliptra/src/soc_ifc/stimulus/testsuites/soc_ifc_nightly_random_regression.yml'
                - timeout: 1440
