# Copyright (C) Microsoft Corporation. All rights reserved.

trigger: none

# Point to another repository for the pipeline template
resources:
  repositories:
  - repository: templates
    type: git
    name: Ether/pipelines
variables:
- group: AHA_POC_Pipelines

stages:
- template: etc/pipelines/templates/promote-pipeline-template.yml@templates  # Template reference
  parameters:
    project: 'AHA_POC'
    repo_url: 'git@ssh.dev.azure.com:v3/ms-tsd/AHA_POC/Caliptra'
    target_branch: 'master'

    build_and_sim_map:
    - integration_top_vcs:
      - display_name: 'Build integration_lib with VCS'
      - enabled: true
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top_tb'
      - args: ''
      - timeout: 30
      - testsuites:
        - l0_regress:
          - enabled: true
          - configspec_name: 'integration_lib'
          - dut: 'caliptra_top_tb'
          - path: 'Caliptra/src/integration/stimulus/L0_regression.yml'

    - integration_top_ius:
      - display_name: 'Build integration_lib with IUS/Xcelium'
      - enabled: false
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top'
      - args: '--tool ius --targets packages rtl elab --options rtl="+define+TSD_DISABLE_ASSERTIONS"'
      - timeout: 10

    design_lint_map:
    - caliptra_top:
      - enabled: false
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top'
      - timeout: 10

    dv_lint_map:
    - caliptra_top_tb:
      - enabled: false
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top_tb'
      - timeout: 10
    
    top_repo: ''
