# Copyright (C) Microsoft Corporation. All rights reserved.

trigger: none

# Point to another repository for the pipeline template
resources:
  repositories:
  - repository: templates
    type: git
    name: Ether/pipelines
variables:
- group: AHA_POC_Pipelines

stages:
- template: etc/pipelines/templates/promote-pipeline-template.yml@templates  # Template reference
  parameters:
    project: 'AHA_POC'
    repo_url: 'git@ssh.dev.azure.com:v3/ms-tsd/AHA_POC/Caliptra'
    target_branch: 'master'
    legal_header: false
    legal_header_warning: false

    # Run repo checks before invoking the actual test steps for earlier
    # detection of basic issues
    pre_test_timeout: 120
    pre_test_steps:
      - script: |
          source /home/continuous_integration/release/enviro/etc/enviro_startup.bash
          module load settings/tsd/pipelines/frontend
          export PYREQUIREMENTS="$(workspace_root)/pipelines/require-progress.txt"
          PROGRESS_CONFIG="$(workspace_root)/progress/config.json"

          # Run the license checker script
          enter-workspace tmp_ws 'echo "running $AHA_POC_REPO/tools/scripts/licenseHeaderCheck.sh" && cd $AHA_POC_REPO && bash $AHA_POC_REPO/tools/scripts/licenseHeaderCheck.sh'

        displayName: 'LICENSE_HEADER_CHECK'
        enabled: true 
        timeoutInMinutes: 5
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)

      - script: |
          source /home/continuous_integration/release/enviro/etc/enviro_startup.bash
          module load settings/tsd/pipelines/frontend
          module load tools/python/python3/3.9.2
          export PYREQUIREMENTS="$(workspace_root)/pipelines/require-progress.txt"
          PROGRESS_CONFIG="$(workspace_root)/progress/config.json"

          enter-workspace tmp_ws 'echo "running $AHA_POC_REPO/tools/scripts/promote_rdl_check.sh" && bash $AHA_POC_REPO/tools/scripts/promote_rdl_check.sh "master"'

        displayName: 'RDL GEN CHECK'
        enabled: true
        timeoutInMinutes: 30
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)

      - script: |
          source /home/continuous_integration/release/enviro/etc/enviro_startup.bash
          module load settings/tsd/pipelines/frontend
          export PYREQUIREMENTS="$(workspace_root)/pipelines/require-progress.txt"
          PROGRESS_CONFIG="$(workspace_root)/progress/config.json"

          # Run the Filelist generator script
          enter-workspace tmp_ws 'echo "running $AHA_POC_REPO/tools/scripts/promote_file_list_check.sh" && bash $AHA_POC_REPO/tools/scripts/promote_file_list_check.sh "master"'

        displayName: 'FILE LIST CHECK'
        enabled: true
        timeoutInMinutes: 90

    build_and_sim_map:
    - integration_top_vcs:
      - display_name: 'Build integration_lib with VCS'
      - enabled: true
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top_tb'
      - args: ''
      - timeout: 30
      - testsuites:
        - l0_regress:
          - enabled: true
          - configspec_name: 'integration_lib'
          - dut: 'caliptra_top_tb'
          - timeout: 75
          - path: 'Caliptra/src/integration/stimulus/L0_regression.yml'

    - integration_top_trng_vcs:
      - display_name: 'Build integration_lib with VCS and enable TRNG'
      - enabled: true
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top_trng_tb'
      - args: ''
      - timeout: 30
      - testsuites:
        - l0_trng_regress:
          - enabled: true
          - configspec_name: 'integration_lib'
          - dut: 'caliptra_top_trng_tb'
          - timeout: 45
          - path: 'Caliptra/src/integration/stimulus/L0_trng_regression.yml'

    - uvmf_soc_ifc:
        - display_name: 'UVMF_SOC_IFC'
        - enabled: true
        - configspec_name: 'integration_lib'
        - dut: 'uvmf_soc_ifc'
        #- args: '--submit-resource-args RAM/28000'
        - testsuites:
          - l0_regress:
            - enabled: true
            - configspec_name: 'integration_lib'
            - dut: 'uvmf_soc_ifc'
            - sim_args: '+CLP_REGRESSION +CLP_SHORT_SUITE +CLP_SEQ=soc_ifc_env_top_mbox_rand_small_sequence +CLP_SEQ=soc_ifc_env_top_mbox_rst_warm_rand_medium_sequence +CLP_SEQ=soc_ifc_env_cptra_init_interrupts_sequence +CLP_SEQ=soc_ifc_env_top_mbox_reg_axs_invalid_medium_sequence'
            - path: '${WORKSPACE}/Caliptra/src/soc_ifc/stimulus/testsuites/uvmf_soc_ifc_promote_regression.yml'
            - timeout: 1440

    - uvmf_caliptra_top:
        - display_name: 'UVMF_CALIPTRA_TOP'
        - enabled: true
        - configspec_name: 'integration_lib'
        - dut: 'uvmf_caliptra_top'
        #- args: '--submit-resource-args RAM/28000'
        - testsuites:
          - l0_regress:
            - enabled: true
            - configspec_name: 'integration_lib'
            - dut: 'uvmf_caliptra_top'
            - sim_args: '+CLP_REGRESSION +CLP_SHORT_SUITE +CLP_SEQ=soc_ifc_env_mbox_rand_small_sequence +CLP_SEQ=soc_ifc_env_mbox_rst_warm_rand_medium_sequence +CLP_SEQ=CLP_RERUN_FW_INIT +CLP_SEQ=soc_ifc_env_mbox_rand_medium_interference_sequence +CLP_SEQ=soc_ifc_env_mbox_fw_upd_sequence'
            - path: '${WORKSPACE}/Caliptra/src/integration/stimulus/testsuites/uvmf_caliptra_top_promote_regression.yml'
            - timeout: 1440

    - integration_top_ius:
      - display_name: 'Build integration_lib with IUS/Xcelium'
      - enabled: false
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top'
      - args: '--tool ius --targets packages rtl elab --options rtl="+define+TSD_DISABLE_ASSERTIONS"'
      - timeout: 10

    design_lint_map:
    - caliptra_top_sglint:
      - enabled: true
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top'
      - lint_tool: 'sglint'
      - timeout: 30
      - args: '--inherit-waivers=True'

    dv_lint_map:
    - caliptra_top_tb:
      - enabled: false
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top_tb'
      - timeout: 10

    top_repo: ''

    additional_test_steps:
      - verilator_smoke_test:
        - display_name: 'Verilator Smoke Test'
        - enabled: true
        - run_in_workspace: True
        - timeout: 120
        - commands:
            - 'set -e'
            - 'module load tools/python/python3/3.9.2'

            # Run the Verilator test regression and dump logfiles to scratch
            - 'submit -i python3 \$AHA_POC_REPO/tools/scripts/run_verilator_l0_regression.py'

      - synthesis_elab_check:
        - display_name: 'Synthesis Elab Check'
        - enabled: true
        - run_in_workspace: True
        - timeout: 10
        - commands:
          - 'set -e'
          - 'module load tools/python/python3/3.9.2'
          #- 'module load tools/synopsys/dc/2020.09-SP1'
          - 'module load tools/synopsys/fusion_compiler/2022.12-SP3'

#          # Run synthesis on top level and exit after elaborate stage
          - 'submit -i python3 \$AHA_POC_REPO/tools/scripts/syn/run_syn.py caliptra_top 1'
