# Copyright (C) Microsoft Corporation. All rights reserved.

trigger: none

# Point to another repository for the pipeline template
resources:
  repositories:
  - repository: templates
    type: git
    name: Ether/pipelines
variables:
- group: AHA_POC_Pipelines

stages:
- template: etc/pipelines/templates/promote-pipeline-template.yml@templates  # Template reference
  parameters:
    project: 'AHA_POC'
    repo_url: 'git@ssh.dev.azure.com:v3/ms-tsd/AHA_POC/Caliptra'
    target_branch: 'master'
    legal_header: false
    legal_header_warning: false

    build_and_sim_map:
    - integration_top_vcs:
      - display_name: 'Build integration_lib with VCS'
      - enabled: true
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top_tb'
      - args: ''
      - timeout: 30
      - testsuites:
        - l0_regress:
          - enabled: true
          - configspec_name: 'integration_lib'
          - dut: 'caliptra_top_tb'
          - timeout: 40
          - path: 'Caliptra/src/integration/stimulus/L0_regression.yml'

    - integration_top_trng_vcs:
      - display_name: 'Build integration_lib with VCS and enable TRNG'
      - enabled: true
      # Run after L0 regression finishes since we rebuild the lib
      - depends_on: 'Regress_integration_top_vcs_l0_regress'
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top_tb'
      - args: '--analyze-args="+define+CALIPTRA_INTERNAL_TRNG"'
      - timeout: 30
      - testsuites:
        - l0_trng_regress:
          - enabled: true
          - configspec_name: 'integration_lib'
          - dut: 'caliptra_top_tb'
          - timeout: 40
          - path: 'Caliptra/src/integration/stimulus/L0_trng_regression.yml'

    - integration_top_ius:
      - display_name: 'Build integration_lib with IUS/Xcelium'
      - enabled: false
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top'
      - args: '--tool ius --targets packages rtl elab --options rtl="+define+TSD_DISABLE_ASSERTIONS"'
      - timeout: 10

    design_lint_map:
    - caliptra_top_sglint:
      - enabled: true
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top'
      - lint_tool: 'sglint'
      - timeout: 30
      - args: '--inherit-waivers=True'

    dv_lint_map:
    - caliptra_top_tb:
      - enabled: false
      - configspec_name: 'integration_lib'
      - dut: 'caliptra_top_tb'
      - timeout: 10

    top_repo: ''

    additional_test_steps:
      - file_list_check:
        - display_name: 'FILE LIST CHECK'
        - enabled: true
        - run_in_workspace: True
        - timeout: 60
        - commands:
            - 'set -e'
            - 'cd \$AHA_POC_REPO'

            # Run the Filelist generator script
            - 'bash \$AHA_POC_REPO/tools/scripts/gen_pb_file_lists.sh'

            # Check for any file changes
            - 'if [[ \$(git status -s --untracked-files=all --ignored=traditional | grep \"\\.vf\" | wc -l) -gt 0 ]]; then
                 echo \"Regenerating VF file lists produced some file changes:\";
                 git status -s --untracked-files=all --ignored=traditional | grep \"\\.vf\";
                 git diff;
                 echo \"*****************************************\";
                 echo \"Review above changes locally and resubmit pipeline\";
                 echo \"(Hint: Check \$AHA_POC_REPO for the above changes)\";
                 echo \"*****************************************\";
                 exit 1;
               fi'
      - license_header_check:
        - display_name: 'LICENSE_HEADER_CHECK'
        - enabled: true 
        - run_in_workspace: True
        - timeout: 5
        - commands: 
          - 'set -e'
          - 'cd \$AHA_POC_REPO'

          # Run the license checker script
          - 'bash \$AHA_POC_REPO/tools/scripts/licenseHeaderCheck.sh'

      - verilator_smoke_test:
        - display_name: 'Verilator Smoke Test'
        - enabled: true
        - run_in_workspace: True
        - timeout: 45
        - commands:
            - 'set -e'
            - 'module load tools/python/python3/3.9.2'

            # Run the Verilator test regression and dump logfiles to scratch
            - 'submit -i python3 \$AHA_POC_REPO/tools/scripts/run_verilator_l0_regression.py'

      - synthesis_elab_check:
        - display_name: 'Synthesis Elab Check'
        - enabled: true
        - run_in_workspace: True
        - timeout: 10
        - commands:
          - 'set -e'
          - 'module load tools/python/python3/3.9.2'
          - 'module load tools/synopsys/dc/2020.09-SP1'

          # Run synthesis on top level and exit after elaborate stage
          - 'submit -i python3 \$AHA_POC_REPO/tools/scripts/syn/run_syn.py caliptra_top 1'
