// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#include "caliptra_defines.h"
#include "caliptra_isr.h"
#include "riscv_hw_if.h"
#include "riscv-csr.h"
#include "printf.h"
#include "ecc.h"

volatile uint32_t* stdout           = (uint32_t *)STDOUT;
volatile uint32_t  intr_count = 0;
#ifdef CPT_VERBOSITY
    enum printf_verbosity verbosity_g = CPT_VERBOSITY;
#else
    enum printf_verbosity verbosity_g = LOW;
#endif

volatile caliptra_intr_received_s cptra_intr_rcv = {0};

/* P-256 test vector (from secp256_testvector.hex generated by ecc_secp256r1.exe).
   Upper 4 dwords are zero; active 256-bit value lives in dwords [4..11] MSW-first. */

void main() {
    VPRINTF(LOW, "----------------------------------\n");
    VPRINTF(LOW, " Running ECC P-256 Det VERIFY Smoke Test !!\n");
    VPRINTF(LOW, "----------------------------------\n");

    uint32_t ecc_msg[] =           {0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0xB37D6700,
                                    0x3B99E49B,
                                    0x770DE71E,
                                    0x5429D527,
                                    0xEA59BA6F,
                                    0xFE7AE6F5,
                                    0x313C44E5,
                                    0x921102A6};
    uint32_t ecc_privkey[] =           {0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0xB57BA11F,
                                    0x3735F3B6,
                                    0x8147151E,
                                    0xB788736D,
                                    0xC6F013A0,
                                    0xBEEBC555,
                                    0xC4317F70,
                                    0x44C5E426};
    uint32_t ecc_pubkey_x[] =           {0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x2DF90173,
                                    0x72533003,
                                    0xF44A693D,
                                    0xB9952A5E,
                                    0xAA889872,
                                    0x1BBE53E7,
                                    0x4473C781,
                                    0x5FB739E9};
    uint32_t ecc_pubkey_y[] =           {0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x3A423A9F,
                                    0xD9B08199,
                                    0x84797AA4,
                                    0x44132704,
                                    0x8FB38315,
                                    0xC1911A1D,
                                    0xB1E7E73B,
                                    0xD9CC932A};
    uint32_t ecc_seed[] =           {0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0xAE6CADE4,
                                    0xA2E25537,
                                    0x0144805E,
                                    0x2557B195,
                                    0x0F68A166,
                                    0x9E6C305B,
                                    0x52C927B3,
                                    0x0DBD60EC};
    uint32_t ecc_nonce[] =           {0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x15925C0A,
                                    0xDE01EDF6,
                                    0x2683F876,
                                    0x9DA2A9DF,
                                    0x91985A1A,
                                    0xE96ABBED,
                                    0x62508DA9,
                                    0xAB7F0E11};
    uint32_t ecc_sign_r[] =           {0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x30E59258,
                                    0x8D80798B,
                                    0xA426855A,
                                    0x06407035,
                                    0xFD2C2CD0,
                                    0x3ADE2B2A,
                                    0xFA6592B5,
                                    0xFAC90FFE};
    uint32_t ecc_sign_s[] =           {0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x1C571D9D,
                                    0xCA33E72F,
                                    0x06F6E4A9,
                                    0xBECB7649,
                                    0x495AF20B,
                                    0x8B67A1EC,
                                    0x2ACB5CEB,
                                    0x65900786};
    uint32_t ecc_iv[] =           {0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0x00000000,
                                    0xE93B8299,
                                    0x3BEA1417,
                                    0xC81B1E72,
                                    0x5191DDD8,
                                    0xC8B3EDA5,
                                    0xE4FE8883,
                                    0xA5D6BB3E,
                                    0xA5D3173F};

    //Call interrupt init
    init_interrupts();

    ecc_io seed;
    ecc_io nonce;
    ecc_io iv;
    ecc_io privkey;
    ecc_io pubkey_x;
    ecc_io pubkey_y;
    ecc_io msg;
    ecc_io sign_r;
    ecc_io sign_s;

    seed.kv_intf = FALSE;
    for (int i = 0; i < 12; i++) seed.data[i] = ecc_seed[i];
    nonce.kv_intf = FALSE;
    for (int i = 0; i < 12; i++) nonce.data[i] = ecc_nonce[i];
    iv.kv_intf = FALSE;
    for (int i = 0; i < 12; i++) iv.data[i] = ecc_iv[i];
    msg.kv_intf = FALSE;
    for (int i = 0; i < 12; i++) msg.data[i] = ecc_msg[i];
    privkey.kv_intf = FALSE;
    for (int i = 0; i < 12; i++) privkey.data[i] = ecc_privkey[i];
    pubkey_x.kv_intf = FALSE;
    for (int i = 0; i < 12; i++) pubkey_x.data[i] = ecc_pubkey_x[i];
    pubkey_y.kv_intf = FALSE;
    for (int i = 0; i < 12; i++) pubkey_y.data[i] = ecc_pubkey_y[i];
    sign_r.kv_intf = FALSE;
    for (int i = 0; i < 12; i++) sign_r.data[i] = ecc_sign_r[i];
    sign_s.kv_intf = FALSE;
    for (int i = 0; i < 12; i++) sign_s.data[i] = ecc_sign_s[i];

    uint8_t curve_sel = 1;
    ecc_verifying_flow(msg, pubkey_x, pubkey_y, sign_r, sign_s, curve_sel);
    cptra_intr_rcv.ecc_notif = 0;

    ecc_zeroize();

    SEND_STDOUT_CTRL(0xff); //End the test
}
