provides: [pv_defines_pkg]
schema_version: 2.4.0
requires: []
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files: 
      - $COMPILE_ROOT/rtl/pv_defines_pkg.sv
      - $COMPILE_ROOT/rtl/pv_macros.svh
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/pv_defines_pkg.sv
      - $COMPILE_ROOT/rtl/pv_macros.svh
---
provides: [pv_uvm_pkg]
schema_version: 2.4.0
targets:
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/pv_reg_uvm.sv
---
provides: [pcrvault]
schema_version: 2.4.0
requires: 
  - libs
  - pv_defines_pkg
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/pv_reg_pkg.sv
      - $COMPILE_ROOT/rtl/pv_reg.sv
      - $COMPILE_ROOT/rtl/pv_defines_pkg.sv
      - $COMPILE_ROOT/rtl/pv.sv
    tops: [pv]
  rtl_lint:
    directories: []
    waiver_files:
      - $COMPILE_ROOT/config/design_lint/pcrvault/sglint_waivers
    black_box:
      - pv_reg
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        #- '-v2k_generate'
