// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//======================================================================
//
// entropy_combiner_align_tb.sv
// ----------------------------
// ES0/ES1 arrival-misalignment stress testbench for the entropy combiner.
//
// The combine result is order-independent: digest = SHA3-384(ES0 || ES1)
// regardless of which entropy_src acks first. This TB drives a CSRNG combine
// request while deliberately skewing the ES0 vs ES1 response latencies to
// stress every arrival ordering:
//     * ES0 first  (es0 latency < es1 latency)
//     * ES1 first  (es1 latency < es0 latency)
//     * simultaneous (equal latencies, including 0)
// across directed sweeps and randomized latency pairs.
//
// Two properties are checked on every request:
//   1. Digest correctness against the reference model (order-independent).
//   2. Handshake ordering: the CSRNG-facing ack must occur strictly AFTER
//      both ES0 and ES1 acks, proving the combiner waited for both seeds
//      before hashing (never acks early on a single source).
//
// AHB/KAT is not exercised (combine mode, strap = 1). Expected digests come
// from tb/entropy_combiner_align_vectors.hex (generated by gen_test_vectors.py).
//
//======================================================================

module entropy_combiner_align_tb
  import entropy_src_pkg::*;
  ();

  //----------------------------------------------------------------
  // Parameters
  //----------------------------------------------------------------
  localparam int    CLK_HALF_PERIOD = 1;
  localparam int    SEED_W          = entropy_src_pkg::CSRNG_BUS_WIDTH; // 384
  localparam int    MAX_LATENCY     = 20;   // max ES response latency stressed
  localparam int    MAX_VECTORS     = 256;
  localparam int    RANDOM_ROUNDS   = 40;   // randomized latency-pair rounds
  localparam string DEFAULT_VEC_FILE = "entropy_combiner_align_vectors.hex";

  //----------------------------------------------------------------
  // Clock / reset
  //----------------------------------------------------------------
  logic clk_tb;
  logic reset_n_tb;
  logic cptra_pwrgood_tb;

  //----------------------------------------------------------------
  // DUT interface signals
  //----------------------------------------------------------------
  entropy_src_hw_if_req_t csrng_req_tb;   // TB  -> DUT
  entropy_src_hw_if_rsp_t csrng_rsp_tb;   // DUT -> TB
  entropy_src_hw_if_req_t es0_req_tb;     // DUT -> ES0 model
  entropy_src_hw_if_rsp_t es0_rsp_tb;     // ES0 model -> DUT
  entropy_src_hw_if_req_t es1_req_tb;     // DUT -> ES1 model
  entropy_src_hw_if_rsp_t es1_rsp_tb;     // ES1 model -> DUT

  logic combine_en_tb;

  // AHB tied off (KAT path intentionally not exercised).
  logic          hresp_tb;
  logic          hreadyout_tb;
  logic [31:0]   hrdata_tb;
  logic          error_intr_tb;
  logic          ahb_lock_tb;

  //----------------------------------------------------------------
  // ES model data and runtime-adjustable latencies
  //----------------------------------------------------------------
  logic [SEED_W-1:0] es0_data_tb;
  logic [SEED_W-1:0] es1_data_tb;
  integer            es0_latency_tb;
  integer            es1_latency_tb;

  logic [SEED_W-1:0] got_digest;
  logic              got_fips;

  integer error_ctr;
  integer tc_ctr;

  //----------------------------------------------------------------
  // Device Under Test
  //----------------------------------------------------------------
  entropy_combiner #(
    .AHB_DATA_WIDTH(32),
    .AHB_ADDR_WIDTH(32)
  ) dut (
    .clk              (clk_tb),
    .reset_n          (reset_n_tb),
    .cptra_pwrgood_i  (cptra_pwrgood_tb),

    .csrng_hw_if_req_i(csrng_req_tb),
    .csrng_hw_if_rsp_o(csrng_rsp_tb),

    .es0_hw_if_req_o  (es0_req_tb),
    .es0_hw_if_rsp_i  (es0_rsp_tb),
    .es1_hw_if_req_o  (es1_req_tb),
    .es1_hw_if_rsp_i  (es1_rsp_tb),

    .combine_en_i     (combine_en_tb),

    // AHB port unused.
    .haddr_i          (32'h0),
    .hwdata_i         (32'h0),
    .hsel_i           (1'b0),
    .hwrite_i         (1'b0),
    .hready_i         (1'b1),
    .htrans_i         (2'b00),
    .hsize_i          (3'b000),

    .hresp_o          (hresp_tb),
    .hreadyout_o      (hreadyout_tb),
    .hrdata_o         (hrdata_tb),

    .error_intr_o     (error_intr_tb),
    .ahb_lock_o       (ahb_lock_tb)
  );

  //----------------------------------------------------------------
  // Clock generator
  //----------------------------------------------------------------
  always #CLK_HALF_PERIOD clk_tb = ~clk_tb;

  //----------------------------------------------------------------
  // Cycle counter + ack-ordering monitor.
  //
  // Records the cycle of the most recent ES0/ES1/CSRNG ack so run_align()
  // can prove the combined ack came strictly after both ES acks.
  //----------------------------------------------------------------
  integer cycle_ctr;
  integer last_es0_ack_cyc;
  integer last_es1_ack_cyc;
  integer last_csrng_ack_cyc;
  always @(posedge clk_tb or negedge reset_n_tb) begin
    if (!reset_n_tb) begin
      cycle_ctr          <= 0;
      last_es0_ack_cyc   <= -1;
      last_es1_ack_cyc   <= -1;
      last_csrng_ack_cyc <= -1;
    end else begin
      cycle_ctr <= cycle_ctr + 1;
      if (es0_rsp_tb.es_ack)   last_es0_ack_cyc   <= cycle_ctr;
      if (es1_rsp_tb.es_ack)   last_es1_ack_cyc   <= cycle_ctr;
      if (csrng_rsp_tb.es_ack) last_csrng_ack_cyc <= cycle_ctr;
    end
  end

  //----------------------------------------------------------------
  // ES0 responder model
  //
  // Mimics entropy_src_ack_sm: while es_req is asserted, after es0_latency_tb
  // cycles it pulses es_ack for one cycle with es_bits/es_fips valid. The
  // `acked` flag prevents a second ack for the same held request.
  //----------------------------------------------------------------
  integer es0_cnt;
  logic   es0_busy;
  logic   es0_acked;
  always @(posedge clk_tb or negedge reset_n_tb) begin
    if (!reset_n_tb) begin
      es0_rsp_tb.es_ack  <= 1'b0;
      es0_rsp_tb.es_bits <= '0;
      es0_rsp_tb.es_fips <= '0;
      es0_cnt            <= 0;
      es0_busy           <= 1'b0;
      es0_acked          <= 1'b0;
    end else begin
      es0_rsp_tb.es_ack <= 1'b0;
      if (!es0_req_tb.es_req) begin
        es0_busy  <= 1'b0;
        es0_acked <= 1'b0;
        es0_cnt   <= 0;
      end else if (!es0_acked) begin
        if (!es0_busy) begin
          es0_busy <= 1'b1;
          es0_cnt  <= es0_latency_tb;
        end else if (es0_cnt == 0) begin
          es0_rsp_tb.es_ack  <= 1'b1;
          es0_rsp_tb.es_bits <= es0_data_tb;
          es0_rsp_tb.es_fips <= 1'b1;
          es0_acked          <= 1'b1;
          es0_busy           <= 1'b0;
        end else begin
          es0_cnt <= es0_cnt - 1;
        end
      end
    end
  end

  //----------------------------------------------------------------
  // ES1 responder model (same protocol, independent latency)
  //----------------------------------------------------------------
  integer es1_cnt;
  logic   es1_busy;
  logic   es1_acked;
  always @(posedge clk_tb or negedge reset_n_tb) begin
    if (!reset_n_tb) begin
      es1_rsp_tb.es_ack  <= 1'b0;
      es1_rsp_tb.es_bits <= '0;
      es1_rsp_tb.es_fips <= '0;
      es1_cnt            <= 0;
      es1_busy           <= 1'b0;
      es1_acked          <= 1'b0;
    end else begin
      es1_rsp_tb.es_ack <= 1'b0;
      if (!es1_req_tb.es_req) begin
        es1_busy  <= 1'b0;
        es1_acked <= 1'b0;
        es1_cnt   <= 0;
      end else if (!es1_acked) begin
        if (!es1_busy) begin
          es1_busy <= 1'b1;
          es1_cnt  <= es1_latency_tb;
        end else if (es1_cnt == 0) begin
          es1_rsp_tb.es_ack  <= 1'b1;
          es1_rsp_tb.es_bits <= es1_data_tb;
          es1_rsp_tb.es_fips <= 1'b1;
          es1_acked          <= 1'b1;
          es1_busy           <= 1'b0;
        end else begin
          es1_cnt <= es1_cnt - 1;
        end
      end
    end
  end

  //----------------------------------------------------------------
  // init_sim()
  //----------------------------------------------------------------
  task init_sim;
    begin
      clk_tb           = 1'b0;
      reset_n_tb       = 1'b0;
      cptra_pwrgood_tb = 1'b0;

      csrng_req_tb     = '0;
      combine_en_tb    = 1'b0;

      es0_data_tb      = '0;
      es1_data_tb      = '0;
      es0_latency_tb   = 2;
      es1_latency_tb   = 2;

      got_digest       = '0;
      got_fips         = 1'b0;

      error_ctr        = 0;
      tc_ctr           = 0;
    end
  endtask

  //----------------------------------------------------------------
  // reset_dut()
  //----------------------------------------------------------------
  task reset_dut;
    begin
      $display("*** Toggle reset.");
      reset_n_tb       = 1'b0;
      cptra_pwrgood_tb = 1'b0;
      repeat (4) @(negedge clk_tb);
      reset_n_tb       = 1'b1;
      cptra_pwrgood_tb = 1'b1;
      repeat (2) @(negedge clk_tb);
    end
  endtask

  //----------------------------------------------------------------
  // wait_csrng_ack()
  //----------------------------------------------------------------
  task wait_csrng_ack;
    integer timeout;
    begin
      timeout    = 0;
      got_digest = '0;
      got_fips   = 1'b0;
      forever begin
        @(negedge clk_tb);
        if (csrng_rsp_tb.es_ack) begin
          got_digest = csrng_rsp_tb.es_bits;
          got_fips   = csrng_rsp_tb.es_fips;
          disable wait_csrng_ack;
        end
        timeout = timeout + 1;
        if (timeout > 2000) begin
          $display("*** ERROR: timeout waiting for CSRNG ack (tc %0d)", tc_ctr);
          error_ctr = error_ctr + 1;
          disable wait_csrng_ack;
        end
      end
    end
  endtask

  //----------------------------------------------------------------
  // run_align()
  //
  // Drives one combine with the given ES0/ES1 latencies and checks both
  // digest correctness and combined-ack-after-both-ES-acks ordering.
  //----------------------------------------------------------------
  task run_align(input logic [SEED_W-1:0] d0,
                 input logic [SEED_W-1:0] d1,
                 input logic [SEED_W-1:0] exp,
                 input integer            l0,
                 input integer            l1,
                 input string             tag);
    integer op_start_cyc;
    string  order;
    begin
      if      (l0 < l1) order = "ES0-first";
      else if (l0 > l1) order = "ES1-first";
      else              order = "simultaneous";

      @(negedge clk_tb);
      es0_latency_tb  = l0;
      es1_latency_tb  = l1;
      es0_data_tb     = d0;
      es1_data_tb     = d1;
      op_start_cyc    = cycle_ctr;
      csrng_req_tb.es_req = 1'b1;

      wait_csrng_ack();

      if (got_digest !== exp) begin
        error_ctr = error_ctr + 1;
        $display("*** [TC %0d] ALIGN %s (%s l0=%0d l1=%0d) DIGEST MISMATCH",
                 tc_ctr, tag, order, l0, l1);
        $display("      exp = %096h", exp);
        $display("      got = %096h", got_digest);
      end else if (got_fips !== 1'b1) begin
        error_ctr = error_ctr + 1;
        $display("*** [TC %0d] ALIGN %s (%s) es_fips MISMATCH exp=1 got=%0b",
                 tc_ctr, tag, order, got_fips);
      end else if (!((last_es0_ack_cyc   >= op_start_cyc) &&
                     (last_es1_ack_cyc   >= op_start_cyc) &&
                     (last_csrng_ack_cyc >  last_es0_ack_cyc) &&
                     (last_csrng_ack_cyc >  last_es1_ack_cyc))) begin
        error_ctr = error_ctr + 1;
        $display("*** [TC %0d] ALIGN %s (%s) ORDER VIOLATION start@%0d es0@%0d es1@%0d csrng@%0d",
                 tc_ctr, tag, order, op_start_cyc,
                 last_es0_ack_cyc, last_es1_ack_cyc, last_csrng_ack_cyc);
      end else begin
        $display("    [TC %0d] ALIGN PASS %-12s l0=%0d l1=%0d  es0@%0d es1@%0d csrng@%0d",
                 tc_ctr, order, l0, l1,
                 last_es0_ack_cyc, last_es1_ack_cyc, last_csrng_ack_cyc);
      end
      tc_ctr = tc_ctr + 1;

      @(negedge clk_tb);
      csrng_req_tb.es_req = 1'b0;
      repeat (6) @(negedge clk_tb);
    end
  endtask

  //----------------------------------------------------------------
  // display_test_result()
  //----------------------------------------------------------------
  task display_test_result;
    begin
      if (error_ctr == 0) begin
        $display("*** All %0d test cases completed successfully.", tc_ctr);
        $display("* TESTCASE PASSED");
      end else begin
        $display("*** %0d test cases completed.", tc_ctr);
        $display("*** %0d errors detected during testing.", error_ctr);
        $display("* TESTCASE FAILED");
      end
    end
  endtask

  //----------------------------------------------------------------
  // Main stimulus
  //----------------------------------------------------------------
  string             vec_file;
  integer            fd;
  integer            scan_ret;
  logic [SEED_W-1:0] v_es0;
  logic [SEED_W-1:0] v_es1;
  logic [SEED_W-1:0] v_exp;

  logic [SEED_W-1:0] es0_arr [MAX_VECTORS];
  logic [SEED_W-1:0] es1_arr [MAX_VECTORS];
  logic [SEED_W-1:0] exp_arr [MAX_VECTORS];
  integer            nvec;

  integer            vi;
  integer            r;
  integer            rl0;
  integer            rl1;

  initial begin
    init_sim();

    if (!$value$plusargs("VEC_FILE=%s", vec_file))
      vec_file = DEFAULT_VEC_FILE;

    // combine_en_i is a static strap sampled at reset; drive it before reset.
    combine_en_tb = 1'b1;
    reset_dut();

    fd = $fopen(vec_file, "r");
    if (fd == 0) begin
      $display("*** ERROR: cannot open vector file '%s'", vec_file);
      $display("* TESTCASE FAILED");
      $finish;
    end
    $display("*** [align strap=1] Loading vectors from '%s'", vec_file);

    nvec = 0;
    while (!$feof(fd) && (nvec < MAX_VECTORS)) begin
      scan_ret = $fscanf(fd, "%h %h %h\n", v_es0, v_es1, v_exp);
      if (scan_ret == 3) begin
        es0_arr[nvec] = v_es0;
        es1_arr[nvec] = v_es1;
        exp_arr[nvec] = v_exp;
        nvec = nvec + 1;
      end
    end
    $fclose(fd);

    if (nvec < 4) begin
      $display("*** ERROR: need >=4 vectors (got %0d)", nvec);
      error_ctr = error_ctr + 1;
      display_test_result();
      $finish;
    end

    //--------------------------------------------------------------
    // Directed alignment matrix: for several data vectors, walk every
    // ordering (simultaneous, ES0-first/ES1-first by small and large skew).
    //--------------------------------------------------------------
    $display("*** [align] Directed ordering matrix");
    for (vi = 0; vi < 4; vi = vi + 1) begin
      run_align(es0_arr[vi], es1_arr[vi], exp_arr[vi], 0,  0,  "equal-0");
      run_align(es0_arr[vi], es1_arr[vi], exp_arr[vi], 3,  3,  "equal-3");
      run_align(es0_arr[vi], es1_arr[vi], exp_arr[vi], 1,  2,  "es0-lead-1");
      run_align(es0_arr[vi], es1_arr[vi], exp_arr[vi], 2,  1,  "es1-lead-1");
      run_align(es0_arr[vi], es1_arr[vi], exp_arr[vi], 1,  MAX_LATENCY, "es0-lead-far");
      run_align(es0_arr[vi], es1_arr[vi], exp_arr[vi], MAX_LATENCY, 1,  "es1-lead-far");
    end

    //--------------------------------------------------------------
    // Randomized latency pairs across random data vectors.
    //--------------------------------------------------------------
    $display("*** [align] Randomized latency pairs");
    for (r = 0; r < RANDOM_ROUNDS; r = r + 1) begin
      vi  = $urandom_range(0, nvec - 1);
      rl0 = $urandom_range(0, MAX_LATENCY);
      rl1 = $urandom_range(0, MAX_LATENCY);
      run_align(es0_arr[vi], es1_arr[vi], exp_arr[vi], rl0, rl1, "random");
    end

    display_test_result();
    $finish;
  end

  //----------------------------------------------------------------
  // Global watchdog
  //----------------------------------------------------------------
  initial begin
    #4_000_000;
    $display("*** ERROR: global simulation timeout.");
    $display("* TESTCASE FAILED");
    $finish;
  end

endmodule
