---
provides: [prim_generic]
schema_version: 2.4.0
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/prim_generic_flop.sv
      - $COMPILE_ROOT/rtl/prim_generic_buf.sv
