$UVMF_VIP_LIBRARY_HOME/interface_packages/soc_ifc_status_pkg/src/soc_ifc_status_if.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/soc_ifc_status_pkg/src/soc_ifc_status_monitor_bfm.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/soc_ifc_status_pkg/src/soc_ifc_status_driver_bfm.sv
