---
provides: [tlul_pkg]
schema_version: 2.4.0
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/tlul_pkg.sv
      - $COMPILE_ROOT/rtl/tlul_adapter_vh.sv
      - $COMPILE_ROOT/rtl/tlul_adapter_reg.sv
      - $COMPILE_ROOT/rtl/tlul_cmd_intg_gen.sv
      - $COMPILE_ROOT/rtl/tlul_cmd_intg_chk.sv
      - $COMPILE_ROOT/rtl/tlul_rsp_intg_gen.sv
      - $COMPILE_ROOT/rtl/tlul_rsp_intg_chk.sv
      - $COMPILE_ROOT/rtl/tlul_data_integ_dec.sv
      - $COMPILE_ROOT/rtl/tlul_data_integ_enc.sv
      - $COMPILE_ROOT/rtl/tlul_err.sv