---
provides: [clp_abr_coverage]  
schema_version: 2.4.0
requires: 
  - abr_top
  - abr_coverage
targets:
  tb:
    directories: 
      - $COMPILE_ROOT/coverage
    files:
      - $COMPILE_ROOT/coverage/clp_abr_top_cov_if.sv
      - $COMPILE_ROOT/coverage/clp_abr_top_cov_bind.sv       