---
provides: [hmac256_drbg]
schema_version: 2.4.0
requires:
  - libs
  - hmac256_ctrl
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/hmac256_drbg.sv
    tops: [hmac256_drbg]
---
provides: [hmac256_drbg_tb]
schema_version: 2.4.0
requires:
  - hmac256_drbg
  - hmac256_drbg_coverage
targets:
  tb:
    directories:
      - $COMPILE_ROOT/tb
    files:
      - $COMPILE_ROOT/tb/hmac256_drbg_tb.sv
    tops: [hmac256_drbg_tb]
  sim:
    pre_exec: 'echo "[PRE-EXEC] Copying HMAC256_DRBG vector generator to $(pwd)" && cp $COMPILE_ROOT/tb/hmac256_drbg_ref.py .'
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - +define+CLP_ASSERT_ON
        - +define+SIMULATION
        - +define+FCOV
        - '-noinherit_timescale=1ns/1ps'
---
provides: [hmac256_drbg_coverage]
schema_version: 2.4.0
requires:
  - hmac256_drbg
targets:
  tb:
    directories:
      - $COMPILE_ROOT/coverage
    files:
      - $COMPILE_ROOT/coverage/hmac256_drbg_cov_if.sv
      - $COMPILE_ROOT/coverage/hmac256_drbg_cov_bind.sv
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - '-noinherit_timescale=1ns/1ps'
