---
provides: [comod_caliptra_ss_top]
schema_version: 2.4.0
requires:
  - caliptra-ss_lib::caliptra_ss_top
targets:
  rtl:
    tops: [caliptra_ss_top]
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - '-sverilog -full64'
        # Used in caliptra_top_sva to find signals
        - +define+CPTRA_TB_TOP_NAME=caliptra_ss_top
        - +define+CPTRA_TOP_PATH=caliptra_ss_top.caliptra_top_dut
        - +define+MCU_RV_BUILD_AXI4
        - +define+MCU_RV_OPENSOURCE
        - +define+AVERY_VCS
        - +define+AVERY_CLOCK=5
        - +define+FOUR_OUTSTANDING
        - +define+AVERY_AXI_INTERCONNECT
        - +define+AAXI_MAX_DATA_WIDTH=64
        - +define+AAXI_MAX_ADDR_WIDTH=64
        - +define+AAXI_MAX_ID_WIDTH=5
        - +define+CALIPTRA_INTERNAL_UART
        - '-noinherit_timescale=1ns/1ps'
        - +define+AAXI_INTC_MASTER_CNT=5
        - +define+AAXI_INTC_SLAVE_CNT=5
        - '/cad/tools/mentor/avery/2.5c/avery_pli-2023_0609/lib.linux/libtb_vcs64.a'
        - '-P /cad/tools/mentor/avery/2.5c/avery_pli-2023_0609/tb_vcs64.tab'
      elab:
        #FIXME implicit-wire-no-fanin and port-connection-width-mismatch warnings from i3c-core
        - '+warn=noIWNF'
        - '+warn=noPCWM-W'
        - '/cad/tools/mentor/avery/2.5c/avery_pli-2023_0609/lib.linux/libtb_vcs64.a'
        - '-P /cad/tools/mentor/avery/2.5c/avery_pli-2023_0609/tb_vcs64.tab'
        #FIXME unique case violations in i3c-core
        - '-ignore unique_checks'
      sim:
        # Uncomment for debug prints
        #- +aaxi_dbg_name=all
        - '+vpi -lpthread'
