uvmf:
  environments:
    soc_ifc:
      imports:
      - name: "rw_txn_pkg"

      agents:
      - name: dummy_avery_aaxi_agent
        type: dummy_avery_aaxi
        initiator_responder: "INITIATOR"
      - name: soc_ifc_ctrl_agent
        type: soc_ifc_ctrl
        initiator_responder: "INITIATOR"
      - name: cptra_ctrl_agent
        type: cptra_ctrl
        initiator_responder: "INITIATOR"
      - name: ss_mode_ctrl_agent
        type: ss_mode_ctrl
        initiator_responder: "INITIATOR"
      - name: soc_ifc_status_agent
        type: soc_ifc_status
        initiator_responder: "RESPONDER"
      - name: cptra_status_agent
        type: cptra_status
        initiator_responder: "RESPONDER"
      - name: ss_mode_status_agent
        type: ss_mode_status
        initiator_responder: "RESPONDER"
      - name: mbox_sram_agent
        type: mbox_sram
        initiator_responder: "RESPONDER"

      analysis_components:
      - name: soc_ifc_pred
        type: soc_ifc_predictor
      - name: soc_ifc_sb
        type: soc_ifc_scoreboard

#      analysis_exports :
#        - name: "ahb_master_0_export"
#          trans_type: "rw_txn"
#          connected_to: "soc_ifc_pred.ahb_master_0_ae"

      analysis_ports: []

      config_constraints: []
      config_vars: []

      parameters: []

      scoreboards: []
#      - name: soc_ifc_sb
#        sb_type: uvmf_in_order_scoreboard
#        trans_type: soc_ifc_status_transaction

      subenvs: []

      qvip_subenvs :
        - { name: "qvip_ahb_lite_slave_subenv", type: "qvip_ahb_lite_slave" }

      qvip_connections :
        - driver: "qvip_ahb_lite_slave_subenv.ahb_lite_slave_0"
          ap_key: "burst_transfer"
          receiver: "soc_ifc_pred.ahb_slave_0_ae"
          validate: "false"

      tlm_connections:
      ############# Predictor connections ############
      - driver: soc_ifc_ctrl_agent.monitored_ap                    # SOC IFC Control
        receiver: soc_ifc_pred.soc_ifc_ctrl_agent_ae               #
      - driver: cptra_ctrl_agent.monitored_ap                      # Caliptra Control
        receiver: soc_ifc_pred.cptra_ctrl_agent_ae                 #
      - driver: ss_mode_ctrl_agent.monitored_ap                    # Subsystem Mode Control
        receiver: soc_ifc_pred.ss_mode_ctrl_agent_ae               #
      - driver: mbox_sram_agent.monitored_ap                       # Mailbox SRAM i/f
        receiver: soc_ifc_pred.mbox_sram_agent_ae                  #
      - driver: dummy_avery_aaxi_agent.monitored_ap                # Dummy AXI placeholder
        receiver: soc_ifc_pred.axi_sub_0_ae                        #
#      - driver: qvip_ahb_lite_master_subenv.ahb_master_0.export_rw # AHB
#        receiver: soc_ifc_pred.ahb_master_0_ae                     #
      ############# Scoreboard connections ############
      # Expected
      - driver: soc_ifc_pred.soc_ifc_sb_ap                    #
        receiver: soc_ifc_sb.expected_analysis_export         #
      - driver: soc_ifc_pred.cptra_sb_ap                      #
        receiver: soc_ifc_sb.expected_cptra_analysis_export   #
      - driver: soc_ifc_pred.ss_mode_sb_ap                    #
        receiver: soc_ifc_sb.expected_ss_mode_analysis_export #
      - driver: soc_ifc_pred.soc_ifc_sb_ahb_ap                #
        receiver: soc_ifc_sb.expected_ahb_analysis_export     #
      - driver: soc_ifc_pred.soc_ifc_sb_axi_ap                #
        receiver: soc_ifc_sb.expected_axi_analysis_export     #
      # Actual
      - driver: soc_ifc_status_agent.monitored_ap           #
        receiver: soc_ifc_sb.actual_analysis_export         #
      - driver: cptra_status_agent.monitored_ap             #
        receiver: soc_ifc_sb.actual_cptra_analysis_export   #
      - driver: ss_mode_status_agent.monitored_ap           #
        receiver: soc_ifc_sb.actual_ss_mode_analysis_export #
#      - driver: 'qvip_ahb_lite_slave_subenv_ahb_lite_slave_0_ap["burst_transfer_sb"]' #
#        receiver: soc_ifc_sb.actual_ahb_analysis_export                               #

      register_model:
        use_adapter: "True"
        use_explicit_prediction: "True"
        reg_block_class: soc_ifc_reg_model_top
        reg_model_package: soc_ifc_reg_model_top_pkg
        maps:
          - name: "fixme_map"
            interface: "qvip_ahb_lite_slave_subenv.ahb_lite_slave_0"
            qvip_agent: "True"
