uvmf:
  environments: 
    fuse_ctrl: 
      agents:
        - name: fuse_ctrl_rst_in_agent
          type: fuse_ctrl_rst_in 
          initiator_responder: "INITIATOR"
        - name: fuse_ctrl_rst_out_agent
          type: fuse_ctrl_rst_out
          initiator_responder: "RESPONDER"
        - name: fuse_ctrl_core_axi_write_in_if_agent
          type: fuse_ctrl_core_axi_write_in 
          initiator_responder: "INITIATOR"
        - name: fuse_ctrl_core_axi_write_out_if_agent
          type: fuse_ctrl_core_axi_write_out 
          initiator_responder: "RESPONDER"
        - name: fuse_ctrl_prim_axi_write_in_if_agent
          type: fuse_ctrl_prim_axi_write_in 
          initiator_responder: "INITIATOR"
        - name: fuse_ctrl_prim_axi_write_out_if_agent
          type: fuse_ctrl_prim_axi_write_out 
          initiator_responder: "RESPONDER"
        - name: fuse_ctrl_core_axi_read_in_if_agent
          type: fuse_ctrl_core_axi_read_in 
          initiator_responder: "INITIATOR"
        - name: fuse_ctrl_core_axi_read_out_if_agent
          type: fuse_ctrl_core_axi_read_out 
          initiator_responder: "RESPONDER"
        - name: fuse_ctrl_prim_axi_read_in_if_agent
          type: fuse_ctrl_prim_axi_read_in
          initiator_responder: "INITIATOR"
        - name: fuse_ctrl_prim_axi_read_out_if_agent
          type: fuse_ctrl_prim_axi_read_out 
          initiator_responder: "RESPONDER"
        - name: fuse_ctrl_secreg_axi_read_in_if_agent
          type: fuse_ctrl_secreg_axi_read_in 
          initiator_responder: "INITIATOR"
        - name: fuse_ctrl_secreg_axi_read_out_if_agent
          type: fuse_ctrl_secreg_axi_read_out 
          initiator_responder: "RESPONDER"
        - name: fuse_ctrl_lc_otp_in_if_agent
          type: fuse_ctrl_lc_otp_in 
          initiator_responder: "INITIATOR"
        - name: fuse_ctrl_lc_otp_out_if_agent
          type: fuse_ctrl_lc_otp_out 
          initiator_responder: "RESPONDER"
        - name: fuse_ctrl_in_if_agent
          type: fuse_ctrl_in
          initiator_responder: "INITIATOR"
        - name: fuse_ctrl_out_if_agent
          type: fuse_ctrl_out
          initiator_responder: "RESPONDER"
      
      analysis_components:
        - name: fuse_ctrl_pred
          type: fuse_ctrl_predictor
        - name: fuse_ctrl_sb
          type: fuse_ctrl_scoreboard

      analysis_ports: []

      config_constraints: []
      config_vars: [] 

      parameters: []

      scoreboards: []

      subenvs: []

      tlm_connections:
        - driver: fuse_ctrl_rst_in_agent.monitored_ap
          receiver: fuse_ctrl_pred.fuse_ctrl_rst_agent_ae
        - driver: fuse_ctrl_pred.fuse_ctrl_sb_ap
          receiver: fuse_ctrl_sb.expected_analysis_export
        - driver: fuse_ctrl_rst_out_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_core_axi_write_in_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_core_axi_write_out_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_core_axi_read_in_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_core_axi_read_out_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_prim_axi_write_in_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_prim_axi_write_out_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_prim_axi_read_in_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_prim_axi_read_out_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_secreg_axi_read_in_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_secreg_axi_read_out_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_lc_otp_in_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_lc_otp_out_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_in_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export
        - driver: fuse_ctrl_out_if_agent.monitored_ap
          receiver: fuse_ctrl_sb.actual_analysis_export

