---
provides: [uvmf_hmac]
schema_version: 2.4.0
requires:
  - uvmf_lib
  - hmac_ctrl
  - hmac_uvm_pkg
  - hmac_coverage
  - keyvault
  - caliptra_top_defines
  - caliptra_top_reg_defines
  - caliptra_prim
targets:
  tb:
    directories:
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/HMAC_rst_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/HMAC_rst_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/HMAC_env_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/HMAC/tb/parameters
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/HMAC/tb/sequences
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/HMAC/tb/tests
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/HMAC/tb/testbench
    files:
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/HMAC_rst_pkg/HMAC_rst_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/HMAC_rst_pkg/HMAC_rst_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/HMAC_rst_pkg/src/HMAC_rst_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/HMAC_rst_pkg/src/HMAC_rst_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/HMAC_rst_pkg/src/HMAC_rst_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/HMAC_env_pkg/registers/HMAC_reg_model_top_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/HMAC_env_pkg/HMAC_env_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/HMAC/tb/parameters/HMAC_parameters_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/HMAC/tb/sequences/HMAC_sequences_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/HMAC/tb/tests/HMAC_tests_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/HMAC/tb/testbench/hdl_top.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/HMAC/tb/testbench/hvl_top.sv
    tops:
      - hdl_top
      - hvl_top
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - +define+CLP_ASSERT_ON
        - +define+SIMULATION
        - +define+FCOV
        - '-noinherit_timescale=1ns/1ps'
        - '+warn=noRVOSFD'
        - '-suppress=SV-LCM-PPWI'
      elab:
        - '-suppress=TFIPC'
        - '-cm line+cond+fsm+tgl+branch+assert'
      sim:
        - '-sv_root $QUESTA_MVC_HOME/questa_mvc_core/linux_x86_64_gcc-6.2.0_vcs'
        - '-sv_lib libahb_IN_SystemVerilog_VCS_full'
        - '+UVM_VERBOSITY=UVM_MEDIUM'
        - '-cm line+cond+fsm+tgl+branch+assert'
