
// This file was autogenerated by PeakRDL-uvm
package entropy_combiner_reg_uvm;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    `include "entropy_combiner_reg_covergroups.svh"
    // Reg - entropy_combiner_reg::COMBINER_NAME
    class entropy_combiner_reg__COMBINER_NAME extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__COMBINER_NAME_bit_cg NAME_bit_cg[32];
        entropy_combiner_reg__COMBINER_NAME_fld_cg fld_cg;
        rand uvm_reg_field NAME;

        function new(string name = "entropy_combiner_reg__COMBINER_NAME");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.NAME = new("NAME");
            this.NAME.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(NAME_bit_cg[bt]) NAME_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__COMBINER_NAME

    // Reg - entropy_combiner_reg::COMBINER_VERSION
    class entropy_combiner_reg__COMBINER_VERSION extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__COMBINER_VERSION_bit_cg VERSION_bit_cg[32];
        entropy_combiner_reg__COMBINER_VERSION_fld_cg fld_cg;
        rand uvm_reg_field VERSION;

        function new(string name = "entropy_combiner_reg__COMBINER_VERSION");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.VERSION = new("VERSION");
            this.VERSION.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(VERSION_bit_cg[bt]) VERSION_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__COMBINER_VERSION

    // Reg - entropy_combiner_reg::KAT_CTRL
    class entropy_combiner_reg__KAT_CTRL extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__KAT_CTRL_bit_cg start_bit_cg[1];
        entropy_combiner_reg__KAT_CTRL_fld_cg fld_cg;
        rand uvm_reg_field start;

        function new(string name = "entropy_combiner_reg__KAT_CTRL");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.start = new("start");
            this.start.configure(this, 1, 0, "WO", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(start_bit_cg[bt]) start_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__KAT_CTRL

    // Reg - entropy_combiner_reg::KAT_MSG_LEN
    class entropy_combiner_reg__KAT_MSG_LEN extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__KAT_MSG_LEN_bit_cg msg_len_bit_cg[32];
        entropy_combiner_reg__KAT_MSG_LEN_fld_cg fld_cg;
        rand uvm_reg_field msg_len;

        function new(string name = "entropy_combiner_reg__KAT_MSG_LEN");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.msg_len = new("msg_len");
            this.msg_len.configure(this, 32, 0, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(msg_len_bit_cg[bt]) msg_len_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__KAT_MSG_LEN

    // Reg - entropy_combiner_reg::KAT_STATUS
    class entropy_combiner_reg__KAT_STATUS extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__KAT_STATUS_bit_cg busy_bit_cg[1];
        entropy_combiner_reg__KAT_STATUS_bit_cg valid_bit_cg[1];
        entropy_combiner_reg__KAT_STATUS_fld_cg fld_cg;
        rand uvm_reg_field busy;
        rand uvm_reg_field valid;

        function new(string name = "entropy_combiner_reg__KAT_STATUS");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.busy = new("busy");
            this.busy.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.valid = new("valid");
            this.valid.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(busy_bit_cg[bt]) busy_bit_cg[bt] = new();
                foreach(valid_bit_cg[bt]) valid_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__KAT_STATUS

    // Reg - entropy_combiner_reg::KAT_MSG
    class entropy_combiner_reg__KAT_MSG extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__KAT_MSG_bit_cg data_bit_cg[32];
        entropy_combiner_reg__KAT_MSG_fld_cg fld_cg;
        rand uvm_reg_field data;

        function new(string name = "entropy_combiner_reg__KAT_MSG");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.data = new("data");
            this.data.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(data_bit_cg[bt]) data_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__KAT_MSG

    // Reg - entropy_combiner_reg::KAT_DIGEST
    class entropy_combiner_reg__KAT_DIGEST extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__KAT_DIGEST_bit_cg data_bit_cg[32];
        entropy_combiner_reg__KAT_DIGEST_fld_cg fld_cg;
        rand uvm_reg_field data;

        function new(string name = "entropy_combiner_reg__KAT_DIGEST");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.data = new("data");
            this.data.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(data_bit_cg[bt]) data_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__KAT_DIGEST

    // Reg - entropy_combiner_reg::COMBINER_CTRL
    class entropy_combiner_reg__COMBINER_CTRL extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__COMBINER_CTRL_bit_cg es_fips_policy_bit_cg[2];
        entropy_combiner_reg__COMBINER_CTRL_bit_cg es_fips_cfg_bit_cg[1];
        entropy_combiner_reg__COMBINER_CTRL_fld_cg fld_cg;
        rand uvm_reg_field es_fips_policy;
        rand uvm_reg_field es_fips_cfg;

        function new(string name = "entropy_combiner_reg__COMBINER_CTRL");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.es_fips_policy = new("es_fips_policy");
            this.es_fips_policy.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
            this.es_fips_cfg = new("es_fips_cfg");
            this.es_fips_cfg.configure(this, 1, 8, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(es_fips_policy_bit_cg[bt]) es_fips_policy_bit_cg[bt] = new();
                foreach(es_fips_cfg_bit_cg[bt]) es_fips_cfg_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__COMBINER_CTRL

    // Reg - entropy_combiner_reg::AHB_LOCK
    class entropy_combiner_reg__AHB_LOCK extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__AHB_LOCK_bit_cg lock_bit_cg[1];
        entropy_combiner_reg__AHB_LOCK_fld_cg fld_cg;
        rand uvm_reg_field lock;

        function new(string name = "entropy_combiner_reg__AHB_LOCK");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.lock = new("lock");
            this.lock.configure(this, 1, 0, "W1S", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(lock_bit_cg[bt]) lock_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__AHB_LOCK

    // Reg - entropy_combiner_reg::COMBINER_STATUS
    class entropy_combiner_reg__COMBINER_STATUS extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__COMBINER_STATUS_bit_cg combine_en_bit_cg[1];
        entropy_combiner_reg__COMBINER_STATUS_fld_cg fld_cg;
        rand uvm_reg_field combine_en;

        function new(string name = "entropy_combiner_reg__COMBINER_STATUS");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.combine_en = new("combine_en");
            this.combine_en.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(combine_en_bit_cg[bt]) combine_en_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__COMBINER_STATUS

    // Reg - entropy_combiner_reg::global_intr_en_t
    class entropy_combiner_reg__global_intr_en_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__global_intr_en_t_bit_cg error_en_bit_cg[1];
        entropy_combiner_reg__global_intr_en_t_bit_cg notif_en_bit_cg[1];
        entropy_combiner_reg__global_intr_en_t_fld_cg fld_cg;
        rand uvm_reg_field error_en;
        rand uvm_reg_field notif_en;

        function new(string name = "entropy_combiner_reg__global_intr_en_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.error_en = new("error_en");
            this.error_en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.notif_en = new("notif_en");
            this.notif_en.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(error_en_bit_cg[bt]) error_en_bit_cg[bt] = new();
                foreach(notif_en_bit_cg[bt]) notif_en_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__global_intr_en_t

    // Reg - entropy_combiner_reg::error_intr_en_t
    class entropy_combiner_reg__error_intr_en_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__error_intr_en_t_bit_cg sha3_error_en_bit_cg[1];
        entropy_combiner_reg__error_intr_en_t_bit_cg sparse_fsm_error_en_bit_cg[1];
        entropy_combiner_reg__error_intr_en_t_bit_cg count_error_en_bit_cg[1];
        entropy_combiner_reg__error_intr_en_t_bit_cg storage_rst_error_en_bit_cg[1];
        entropy_combiner_reg__error_intr_en_t_fld_cg fld_cg;
        rand uvm_reg_field sha3_error_en;
        rand uvm_reg_field sparse_fsm_error_en;
        rand uvm_reg_field count_error_en;
        rand uvm_reg_field storage_rst_error_en;

        function new(string name = "entropy_combiner_reg__error_intr_en_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.sha3_error_en = new("sha3_error_en");
            this.sha3_error_en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.sparse_fsm_error_en = new("sparse_fsm_error_en");
            this.sparse_fsm_error_en.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            this.count_error_en = new("count_error_en");
            this.count_error_en.configure(this, 1, 2, "RW", 0, 'h0, 1, 1, 0);
            this.storage_rst_error_en = new("storage_rst_error_en");
            this.storage_rst_error_en.configure(this, 1, 3, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(sha3_error_en_bit_cg[bt]) sha3_error_en_bit_cg[bt] = new();
                foreach(sparse_fsm_error_en_bit_cg[bt]) sparse_fsm_error_en_bit_cg[bt] = new();
                foreach(count_error_en_bit_cg[bt]) count_error_en_bit_cg[bt] = new();
                foreach(storage_rst_error_en_bit_cg[bt]) storage_rst_error_en_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__error_intr_en_t

    // Reg - entropy_combiner_reg::notif_intr_en_t
    class entropy_combiner_reg__notif_intr_en_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__notif_intr_en_t_bit_cg notif_kat_done_en_bit_cg[1];
        entropy_combiner_reg__notif_intr_en_t_fld_cg fld_cg;
        rand uvm_reg_field notif_kat_done_en;

        function new(string name = "entropy_combiner_reg__notif_intr_en_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.notif_kat_done_en = new("notif_kat_done_en");
            this.notif_kat_done_en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(notif_kat_done_en_bit_cg[bt]) notif_kat_done_en_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__notif_intr_en_t

    // Reg - entropy_combiner_reg::global_intr_t_agg_sts_dd3dcf0a
    class entropy_combiner_reg__global_intr_t_agg_sts_dd3dcf0a extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__global_intr_t_agg_sts_dd3dcf0a_bit_cg agg_sts_bit_cg[1];
        entropy_combiner_reg__global_intr_t_agg_sts_dd3dcf0a_fld_cg fld_cg;
        rand uvm_reg_field agg_sts;

        function new(string name = "entropy_combiner_reg__global_intr_t_agg_sts_dd3dcf0a");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.agg_sts = new("agg_sts");
            this.agg_sts.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(agg_sts_bit_cg[bt]) agg_sts_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__global_intr_t_agg_sts_dd3dcf0a

    // Reg - entropy_combiner_reg::global_intr_t_agg_sts_e6399b4a
    class entropy_combiner_reg__global_intr_t_agg_sts_e6399b4a extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__global_intr_t_agg_sts_e6399b4a_bit_cg agg_sts_bit_cg[1];
        entropy_combiner_reg__global_intr_t_agg_sts_e6399b4a_fld_cg fld_cg;
        rand uvm_reg_field agg_sts;

        function new(string name = "entropy_combiner_reg__global_intr_t_agg_sts_e6399b4a");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.agg_sts = new("agg_sts");
            this.agg_sts.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(agg_sts_bit_cg[bt]) agg_sts_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__global_intr_t_agg_sts_e6399b4a

    // Reg - entropy_combiner_reg::error_intr_t_count_error_sts_3599d16f_sha3_error_sts_a3cfdcf2_sparse_fsm_error_sts_eed28f3e_storage_rst_error_sts_a4339a40
    class entropy_combiner_reg__error_intr_t_count_error_sts_3599d16f_sha3_error_sts_a3cfdcf2_sparse_fsm_error_sts_eed28f3e_storage_rst_error_sts_a4339a40 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__error_intr_t_count_error_sts_3599d16f_sha3_error_sts_a3cfdcf2_sparse_fsm_error_sts_eed28f3e_storage_rst_error_sts_a4339a40_bit_cg sha3_error_sts_bit_cg[1];
        entropy_combiner_reg__error_intr_t_count_error_sts_3599d16f_sha3_error_sts_a3cfdcf2_sparse_fsm_error_sts_eed28f3e_storage_rst_error_sts_a4339a40_bit_cg sparse_fsm_error_sts_bit_cg[1];
        entropy_combiner_reg__error_intr_t_count_error_sts_3599d16f_sha3_error_sts_a3cfdcf2_sparse_fsm_error_sts_eed28f3e_storage_rst_error_sts_a4339a40_bit_cg count_error_sts_bit_cg[1];
        entropy_combiner_reg__error_intr_t_count_error_sts_3599d16f_sha3_error_sts_a3cfdcf2_sparse_fsm_error_sts_eed28f3e_storage_rst_error_sts_a4339a40_bit_cg storage_rst_error_sts_bit_cg[1];
        entropy_combiner_reg__error_intr_t_count_error_sts_3599d16f_sha3_error_sts_a3cfdcf2_sparse_fsm_error_sts_eed28f3e_storage_rst_error_sts_a4339a40_fld_cg fld_cg;
        rand uvm_reg_field sha3_error_sts;
        rand uvm_reg_field sparse_fsm_error_sts;
        rand uvm_reg_field count_error_sts;
        rand uvm_reg_field storage_rst_error_sts;

        function new(string name = "entropy_combiner_reg__error_intr_t_count_error_sts_3599d16f_sha3_error_sts_a3cfdcf2_sparse_fsm_error_sts_eed28f3e_storage_rst_error_sts_a4339a40");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.sha3_error_sts = new("sha3_error_sts");
            this.sha3_error_sts.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            this.sparse_fsm_error_sts = new("sparse_fsm_error_sts");
            this.sparse_fsm_error_sts.configure(this, 1, 1, "W1C", 1, 'h0, 1, 1, 0);
            this.count_error_sts = new("count_error_sts");
            this.count_error_sts.configure(this, 1, 2, "W1C", 1, 'h0, 1, 1, 0);
            this.storage_rst_error_sts = new("storage_rst_error_sts");
            this.storage_rst_error_sts.configure(this, 1, 3, "W1C", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(sha3_error_sts_bit_cg[bt]) sha3_error_sts_bit_cg[bt] = new();
                foreach(sparse_fsm_error_sts_bit_cg[bt]) sparse_fsm_error_sts_bit_cg[bt] = new();
                foreach(count_error_sts_bit_cg[bt]) count_error_sts_bit_cg[bt] = new();
                foreach(storage_rst_error_sts_bit_cg[bt]) storage_rst_error_sts_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__error_intr_t_count_error_sts_3599d16f_sha3_error_sts_a3cfdcf2_sparse_fsm_error_sts_eed28f3e_storage_rst_error_sts_a4339a40

    // Reg - entropy_combiner_reg::notif_intr_t_notif_kat_done_sts_50d04acb
    class entropy_combiner_reg__notif_intr_t_notif_kat_done_sts_50d04acb extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__notif_intr_t_notif_kat_done_sts_50d04acb_bit_cg notif_kat_done_sts_bit_cg[1];
        entropy_combiner_reg__notif_intr_t_notif_kat_done_sts_50d04acb_fld_cg fld_cg;
        rand uvm_reg_field notif_kat_done_sts;

        function new(string name = "entropy_combiner_reg__notif_intr_t_notif_kat_done_sts_50d04acb");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.notif_kat_done_sts = new("notif_kat_done_sts");
            this.notif_kat_done_sts.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(notif_kat_done_sts_bit_cg[bt]) notif_kat_done_sts_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__notif_intr_t_notif_kat_done_sts_50d04acb

    // Reg - entropy_combiner_reg::error_intr_trig_t
    class entropy_combiner_reg__error_intr_trig_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__error_intr_trig_t_bit_cg sha3_error_trig_bit_cg[1];
        entropy_combiner_reg__error_intr_trig_t_bit_cg sparse_fsm_error_trig_bit_cg[1];
        entropy_combiner_reg__error_intr_trig_t_bit_cg count_error_trig_bit_cg[1];
        entropy_combiner_reg__error_intr_trig_t_bit_cg storage_rst_error_trig_bit_cg[1];
        entropy_combiner_reg__error_intr_trig_t_fld_cg fld_cg;
        rand uvm_reg_field sha3_error_trig;
        rand uvm_reg_field sparse_fsm_error_trig;
        rand uvm_reg_field count_error_trig;
        rand uvm_reg_field storage_rst_error_trig;

        function new(string name = "entropy_combiner_reg__error_intr_trig_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.sha3_error_trig = new("sha3_error_trig");
            this.sha3_error_trig.configure(this, 1, 0, "W1S", 0, 'h0, 1, 1, 0);
            this.sparse_fsm_error_trig = new("sparse_fsm_error_trig");
            this.sparse_fsm_error_trig.configure(this, 1, 1, "W1S", 0, 'h0, 1, 1, 0);
            this.count_error_trig = new("count_error_trig");
            this.count_error_trig.configure(this, 1, 2, "W1S", 0, 'h0, 1, 1, 0);
            this.storage_rst_error_trig = new("storage_rst_error_trig");
            this.storage_rst_error_trig.configure(this, 1, 3, "W1S", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(sha3_error_trig_bit_cg[bt]) sha3_error_trig_bit_cg[bt] = new();
                foreach(sparse_fsm_error_trig_bit_cg[bt]) sparse_fsm_error_trig_bit_cg[bt] = new();
                foreach(count_error_trig_bit_cg[bt]) count_error_trig_bit_cg[bt] = new();
                foreach(storage_rst_error_trig_bit_cg[bt]) storage_rst_error_trig_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__error_intr_trig_t

    // Reg - entropy_combiner_reg::notif_intr_trig_t
    class entropy_combiner_reg__notif_intr_trig_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__notif_intr_trig_t_bit_cg notif_kat_done_trig_bit_cg[1];
        entropy_combiner_reg__notif_intr_trig_t_fld_cg fld_cg;
        rand uvm_reg_field notif_kat_done_trig;

        function new(string name = "entropy_combiner_reg__notif_intr_trig_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.notif_kat_done_trig = new("notif_kat_done_trig");
            this.notif_kat_done_trig.configure(this, 1, 0, "W1S", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(notif_kat_done_trig_bit_cg[bt]) notif_kat_done_trig_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__notif_intr_trig_t

    // Reg - entropy_combiner_reg::intr_count_t_cnt_9198fa18
    class entropy_combiner_reg__intr_count_t_cnt_9198fa18 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__intr_count_t_cnt_9198fa18_bit_cg cnt_bit_cg[32];
        entropy_combiner_reg__intr_count_t_cnt_9198fa18_fld_cg fld_cg;
        rand uvm_reg_field cnt;

        function new(string name = "entropy_combiner_reg__intr_count_t_cnt_9198fa18");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.cnt = new("cnt");
            this.cnt.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(cnt_bit_cg[bt]) cnt_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__intr_count_t_cnt_9198fa18

    // Reg - entropy_combiner_reg::intr_count_t_cnt_d64d6c2f
    class entropy_combiner_reg__intr_count_t_cnt_d64d6c2f extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__intr_count_t_cnt_d64d6c2f_bit_cg cnt_bit_cg[32];
        entropy_combiner_reg__intr_count_t_cnt_d64d6c2f_fld_cg fld_cg;
        rand uvm_reg_field cnt;

        function new(string name = "entropy_combiner_reg__intr_count_t_cnt_d64d6c2f");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.cnt = new("cnt");
            this.cnt.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(cnt_bit_cg[bt]) cnt_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__intr_count_t_cnt_d64d6c2f

    // Reg - entropy_combiner_reg::intr_count_t_cnt_855566f4
    class entropy_combiner_reg__intr_count_t_cnt_855566f4 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__intr_count_t_cnt_855566f4_bit_cg cnt_bit_cg[32];
        entropy_combiner_reg__intr_count_t_cnt_855566f4_fld_cg fld_cg;
        rand uvm_reg_field cnt;

        function new(string name = "entropy_combiner_reg__intr_count_t_cnt_855566f4");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.cnt = new("cnt");
            this.cnt.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(cnt_bit_cg[bt]) cnt_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__intr_count_t_cnt_855566f4

    // Reg - entropy_combiner_reg::intr_count_t_cnt_2f455042
    class entropy_combiner_reg__intr_count_t_cnt_2f455042 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__intr_count_t_cnt_2f455042_bit_cg cnt_bit_cg[32];
        entropy_combiner_reg__intr_count_t_cnt_2f455042_fld_cg fld_cg;
        rand uvm_reg_field cnt;

        function new(string name = "entropy_combiner_reg__intr_count_t_cnt_2f455042");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.cnt = new("cnt");
            this.cnt.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(cnt_bit_cg[bt]) cnt_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__intr_count_t_cnt_2f455042

    // Reg - entropy_combiner_reg::intr_count_t_cnt_dd5595d5
    class entropy_combiner_reg__intr_count_t_cnt_dd5595d5 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__intr_count_t_cnt_dd5595d5_bit_cg cnt_bit_cg[32];
        entropy_combiner_reg__intr_count_t_cnt_dd5595d5_fld_cg fld_cg;
        rand uvm_reg_field cnt;

        function new(string name = "entropy_combiner_reg__intr_count_t_cnt_dd5595d5");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.cnt = new("cnt");
            this.cnt.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(cnt_bit_cg[bt]) cnt_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__intr_count_t_cnt_dd5595d5

    // Reg - entropy_combiner_reg::intr_count_incr_t_pulse_d65b5e88
    class entropy_combiner_reg__intr_count_incr_t_pulse_d65b5e88 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__intr_count_incr_t_pulse_d65b5e88_bit_cg pulse_bit_cg[1];
        entropy_combiner_reg__intr_count_incr_t_pulse_d65b5e88_fld_cg fld_cg;
        rand uvm_reg_field pulse;

        function new(string name = "entropy_combiner_reg__intr_count_incr_t_pulse_d65b5e88");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.pulse = new("pulse");
            this.pulse.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(pulse_bit_cg[bt]) pulse_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__intr_count_incr_t_pulse_d65b5e88

    // Reg - entropy_combiner_reg::intr_count_incr_t_pulse_a1bb0d16
    class entropy_combiner_reg__intr_count_incr_t_pulse_a1bb0d16 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__intr_count_incr_t_pulse_a1bb0d16_bit_cg pulse_bit_cg[1];
        entropy_combiner_reg__intr_count_incr_t_pulse_a1bb0d16_fld_cg fld_cg;
        rand uvm_reg_field pulse;

        function new(string name = "entropy_combiner_reg__intr_count_incr_t_pulse_a1bb0d16");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.pulse = new("pulse");
            this.pulse.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(pulse_bit_cg[bt]) pulse_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__intr_count_incr_t_pulse_a1bb0d16

    // Reg - entropy_combiner_reg::intr_count_incr_t_pulse_d619a058
    class entropy_combiner_reg__intr_count_incr_t_pulse_d619a058 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__intr_count_incr_t_pulse_d619a058_bit_cg pulse_bit_cg[1];
        entropy_combiner_reg__intr_count_incr_t_pulse_d619a058_fld_cg fld_cg;
        rand uvm_reg_field pulse;

        function new(string name = "entropy_combiner_reg__intr_count_incr_t_pulse_d619a058");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.pulse = new("pulse");
            this.pulse.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(pulse_bit_cg[bt]) pulse_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__intr_count_incr_t_pulse_d619a058

    // Reg - entropy_combiner_reg::intr_count_incr_t_pulse_e5766d33
    class entropy_combiner_reg__intr_count_incr_t_pulse_e5766d33 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__intr_count_incr_t_pulse_e5766d33_bit_cg pulse_bit_cg[1];
        entropy_combiner_reg__intr_count_incr_t_pulse_e5766d33_fld_cg fld_cg;
        rand uvm_reg_field pulse;

        function new(string name = "entropy_combiner_reg__intr_count_incr_t_pulse_e5766d33");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.pulse = new("pulse");
            this.pulse.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(pulse_bit_cg[bt]) pulse_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__intr_count_incr_t_pulse_e5766d33

    // Reg - entropy_combiner_reg::intr_count_incr_t_pulse_4d47d41f
    class entropy_combiner_reg__intr_count_incr_t_pulse_4d47d41f extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        entropy_combiner_reg__intr_count_incr_t_pulse_4d47d41f_bit_cg pulse_bit_cg[1];
        entropy_combiner_reg__intr_count_incr_t_pulse_4d47d41f_fld_cg fld_cg;
        rand uvm_reg_field pulse;

        function new(string name = "entropy_combiner_reg__intr_count_incr_t_pulse_4d47d41f");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.pulse = new("pulse");
            this.pulse.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(pulse_bit_cg[bt]) pulse_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : entropy_combiner_reg__intr_count_incr_t_pulse_4d47d41f

    // Regfile - entropy_combiner_reg::intr_block_t
    class entropy_combiner_reg__intr_block_t extends uvm_reg_block;
        rand entropy_combiner_reg__global_intr_en_t global_intr_en_r;
        rand entropy_combiner_reg__error_intr_en_t error_intr_en_r;
        rand entropy_combiner_reg__notif_intr_en_t notif_intr_en_r;
        rand entropy_combiner_reg__global_intr_t_agg_sts_dd3dcf0a error_global_intr_r;
        rand entropy_combiner_reg__global_intr_t_agg_sts_e6399b4a notif_global_intr_r;
        rand entropy_combiner_reg__error_intr_t_count_error_sts_3599d16f_sha3_error_sts_a3cfdcf2_sparse_fsm_error_sts_eed28f3e_storage_rst_error_sts_a4339a40 error_internal_intr_r;
        rand entropy_combiner_reg__notif_intr_t_notif_kat_done_sts_50d04acb notif_internal_intr_r;
        rand entropy_combiner_reg__error_intr_trig_t error_intr_trig_r;
        rand entropy_combiner_reg__notif_intr_trig_t notif_intr_trig_r;
        rand entropy_combiner_reg__intr_count_t_cnt_9198fa18 sha3_error_intr_count_r;
        rand entropy_combiner_reg__intr_count_t_cnt_d64d6c2f sparse_fsm_error_intr_count_r;
        rand entropy_combiner_reg__intr_count_t_cnt_855566f4 count_error_intr_count_r;
        rand entropy_combiner_reg__intr_count_t_cnt_2f455042 storage_rst_error_intr_count_r;
        rand entropy_combiner_reg__intr_count_t_cnt_dd5595d5 notif_kat_done_intr_count_r;
        rand entropy_combiner_reg__intr_count_incr_t_pulse_d65b5e88 sha3_error_intr_count_incr_r;
        rand entropy_combiner_reg__intr_count_incr_t_pulse_a1bb0d16 sparse_fsm_error_intr_count_incr_r;
        rand entropy_combiner_reg__intr_count_incr_t_pulse_d619a058 count_error_intr_count_incr_r;
        rand entropy_combiner_reg__intr_count_incr_t_pulse_e5766d33 storage_rst_error_intr_count_incr_r;
        rand entropy_combiner_reg__intr_count_incr_t_pulse_4d47d41f notif_kat_done_intr_count_incr_r;

        function new(string name = "entropy_combiner_reg__intr_block_t");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.global_intr_en_r = new("global_intr_en_r");
            this.global_intr_en_r.configure(this);

            this.global_intr_en_r.build();
            this.default_map.add_reg(this.global_intr_en_r, 'h0);
            this.error_intr_en_r = new("error_intr_en_r");
            this.error_intr_en_r.configure(this);

            this.error_intr_en_r.build();
            this.default_map.add_reg(this.error_intr_en_r, 'h4);
            this.notif_intr_en_r = new("notif_intr_en_r");
            this.notif_intr_en_r.configure(this);

            this.notif_intr_en_r.build();
            this.default_map.add_reg(this.notif_intr_en_r, 'h8);
            this.error_global_intr_r = new("error_global_intr_r");
            this.error_global_intr_r.configure(this);

            this.error_global_intr_r.build();
            this.default_map.add_reg(this.error_global_intr_r, 'hc);
            this.notif_global_intr_r = new("notif_global_intr_r");
            this.notif_global_intr_r.configure(this);

            this.notif_global_intr_r.build();
            this.default_map.add_reg(this.notif_global_intr_r, 'h10);
            this.error_internal_intr_r = new("error_internal_intr_r");
            this.error_internal_intr_r.configure(this);

            this.error_internal_intr_r.build();
            this.default_map.add_reg(this.error_internal_intr_r, 'h14);
            this.notif_internal_intr_r = new("notif_internal_intr_r");
            this.notif_internal_intr_r.configure(this);

            this.notif_internal_intr_r.build();
            this.default_map.add_reg(this.notif_internal_intr_r, 'h18);
            this.error_intr_trig_r = new("error_intr_trig_r");
            this.error_intr_trig_r.configure(this);

            this.error_intr_trig_r.build();
            this.default_map.add_reg(this.error_intr_trig_r, 'h1c);
            this.notif_intr_trig_r = new("notif_intr_trig_r");
            this.notif_intr_trig_r.configure(this);

            this.notif_intr_trig_r.build();
            this.default_map.add_reg(this.notif_intr_trig_r, 'h20);
            this.sha3_error_intr_count_r = new("sha3_error_intr_count_r");
            this.sha3_error_intr_count_r.configure(this);

            this.sha3_error_intr_count_r.build();
            this.default_map.add_reg(this.sha3_error_intr_count_r, 'h100);
            this.sparse_fsm_error_intr_count_r = new("sparse_fsm_error_intr_count_r");
            this.sparse_fsm_error_intr_count_r.configure(this);

            this.sparse_fsm_error_intr_count_r.build();
            this.default_map.add_reg(this.sparse_fsm_error_intr_count_r, 'h104);
            this.count_error_intr_count_r = new("count_error_intr_count_r");
            this.count_error_intr_count_r.configure(this);

            this.count_error_intr_count_r.build();
            this.default_map.add_reg(this.count_error_intr_count_r, 'h108);
            this.storage_rst_error_intr_count_r = new("storage_rst_error_intr_count_r");
            this.storage_rst_error_intr_count_r.configure(this);

            this.storage_rst_error_intr_count_r.build();
            this.default_map.add_reg(this.storage_rst_error_intr_count_r, 'h10c);
            this.notif_kat_done_intr_count_r = new("notif_kat_done_intr_count_r");
            this.notif_kat_done_intr_count_r.configure(this);

            this.notif_kat_done_intr_count_r.build();
            this.default_map.add_reg(this.notif_kat_done_intr_count_r, 'h180);
            this.sha3_error_intr_count_incr_r = new("sha3_error_intr_count_incr_r");
            this.sha3_error_intr_count_incr_r.configure(this);

            this.sha3_error_intr_count_incr_r.build();
            this.default_map.add_reg(this.sha3_error_intr_count_incr_r, 'h200);
            this.sparse_fsm_error_intr_count_incr_r = new("sparse_fsm_error_intr_count_incr_r");
            this.sparse_fsm_error_intr_count_incr_r.configure(this);

            this.sparse_fsm_error_intr_count_incr_r.build();
            this.default_map.add_reg(this.sparse_fsm_error_intr_count_incr_r, 'h204);
            this.count_error_intr_count_incr_r = new("count_error_intr_count_incr_r");
            this.count_error_intr_count_incr_r.configure(this);

            this.count_error_intr_count_incr_r.build();
            this.default_map.add_reg(this.count_error_intr_count_incr_r, 'h208);
            this.storage_rst_error_intr_count_incr_r = new("storage_rst_error_intr_count_incr_r");
            this.storage_rst_error_intr_count_incr_r.configure(this);

            this.storage_rst_error_intr_count_incr_r.build();
            this.default_map.add_reg(this.storage_rst_error_intr_count_incr_r, 'h20c);
            this.notif_kat_done_intr_count_incr_r = new("notif_kat_done_intr_count_incr_r");
            this.notif_kat_done_intr_count_incr_r.configure(this);

            this.notif_kat_done_intr_count_incr_r.build();
            this.default_map.add_reg(this.notif_kat_done_intr_count_incr_r, 'h210);
        endfunction : build
    endclass : entropy_combiner_reg__intr_block_t

    // Addrmap - entropy_combiner_reg
    class entropy_combiner_reg extends uvm_reg_block;
        rand entropy_combiner_reg__COMBINER_NAME COMBINER_NAME[2];
        rand entropy_combiner_reg__COMBINER_VERSION COMBINER_VERSION[2];
        rand entropy_combiner_reg__KAT_CTRL KAT_CTRL;
        rand entropy_combiner_reg__KAT_MSG_LEN KAT_MSG_LEN;
        rand entropy_combiner_reg__KAT_STATUS KAT_STATUS;
        rand entropy_combiner_reg__KAT_MSG KAT_MSG[24];
        rand entropy_combiner_reg__KAT_DIGEST KAT_DIGEST[12];
        rand entropy_combiner_reg__COMBINER_CTRL COMBINER_CTRL;
        rand entropy_combiner_reg__AHB_LOCK AHB_LOCK;
        rand entropy_combiner_reg__COMBINER_STATUS COMBINER_STATUS;
        rand entropy_combiner_reg__intr_block_t intr_block_rf;

        function new(string name = "entropy_combiner_reg");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            foreach(this.COMBINER_NAME[i0]) begin
                this.COMBINER_NAME[i0] = new($sformatf("COMBINER_NAME[%0d]", i0));
                this.COMBINER_NAME[i0].configure(this);
                
                this.COMBINER_NAME[i0].build();
                this.default_map.add_reg(this.COMBINER_NAME[i0], 'h0 + i0*'h4);
            end
            foreach(this.COMBINER_VERSION[i0]) begin
                this.COMBINER_VERSION[i0] = new($sformatf("COMBINER_VERSION[%0d]", i0));
                this.COMBINER_VERSION[i0].configure(this);
                
                this.COMBINER_VERSION[i0].build();
                this.default_map.add_reg(this.COMBINER_VERSION[i0], 'h8 + i0*'h4);
            end
            this.KAT_CTRL = new("KAT_CTRL");
            this.KAT_CTRL.configure(this);

            this.KAT_CTRL.build();
            this.default_map.add_reg(this.KAT_CTRL, 'h10);
            this.KAT_MSG_LEN = new("KAT_MSG_LEN");
            this.KAT_MSG_LEN.configure(this);

            this.KAT_MSG_LEN.build();
            this.default_map.add_reg(this.KAT_MSG_LEN, 'h14);
            this.KAT_STATUS = new("KAT_STATUS");
            this.KAT_STATUS.configure(this);

            this.KAT_STATUS.build();
            this.default_map.add_reg(this.KAT_STATUS, 'h18);
            foreach(this.KAT_MSG[i0]) begin
                this.KAT_MSG[i0] = new($sformatf("KAT_MSG[%0d]", i0));
                this.KAT_MSG[i0].configure(this);
                
                this.KAT_MSG[i0].build();
                this.default_map.add_reg(this.KAT_MSG[i0], 'h1c + i0*'h4);
            end
            foreach(this.KAT_DIGEST[i0]) begin
                this.KAT_DIGEST[i0] = new($sformatf("KAT_DIGEST[%0d]", i0));
                this.KAT_DIGEST[i0].configure(this);
                
                this.KAT_DIGEST[i0].build();
                this.default_map.add_reg(this.KAT_DIGEST[i0], 'h7c + i0*'h4);
            end
            this.COMBINER_CTRL = new("COMBINER_CTRL");
            this.COMBINER_CTRL.configure(this);

            this.COMBINER_CTRL.build();
            this.default_map.add_reg(this.COMBINER_CTRL, 'hac);
            this.AHB_LOCK = new("AHB_LOCK");
            this.AHB_LOCK.configure(this);

            this.AHB_LOCK.build();
            this.default_map.add_reg(this.AHB_LOCK, 'hb0);
            this.COMBINER_STATUS = new("COMBINER_STATUS");
            this.COMBINER_STATUS.configure(this);

            this.COMBINER_STATUS.build();
            this.default_map.add_reg(this.COMBINER_STATUS, 'hb4);
            this.intr_block_rf = new("intr_block_rf");
            this.intr_block_rf.configure(this);
            this.intr_block_rf.build();
            this.default_map.add_submap(this.intr_block_rf.default_map, 'h400);
        endfunction : build
    endclass : entropy_combiner_reg

    `include "entropy_combiner_reg_sample.svh"
endpackage: entropy_combiner_reg_uvm
