---
provides: [prim_pkg]
schema_version: 2.4.0
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/prim_util_pkg.sv
      - $COMPILE_ROOT/rtl/prim_alert_pkg.sv
      - $COMPILE_ROOT/rtl/prim_subreg_pkg.sv
      - $COMPILE_ROOT/rtl/prim_mubi_pkg.sv
      - $COMPILE_ROOT/rtl/prim_cipher_pkg.sv
      - $COMPILE_ROOT/rtl/prim_pkg.sv
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/prim_util_pkg.sv
      - $COMPILE_ROOT/rtl/prim_alert_pkg.sv
      - $COMPILE_ROOT/rtl/prim_subreg_pkg.sv
      - $COMPILE_ROOT/rtl/prim_mubi_pkg.sv
      - $COMPILE_ROOT/rtl/prim_cipher_pkg.sv
      - $COMPILE_ROOT/rtl/prim_pkg.sv
---
provides: [prim]
schema_version: 2.4.0
requires:
  - libs
  - lc_ctrl_pkg
  - prim_pkg
  - prim_generic
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
#      - $COMPILE_ROOT/rtl/prim_flop_macros.sv
      - $COMPILE_ROOT/rtl/prim_flop_2sync.sv
      - $COMPILE_ROOT/rtl/prim_lfsr.sv
      - $COMPILE_ROOT/rtl/prim_mubi4_sync.sv
      - $COMPILE_ROOT/rtl/prim_diff_decode.sv
      - $COMPILE_ROOT/rtl/prim_sec_anchor_buf.sv
      - $COMPILE_ROOT/rtl/prim_slicer.sv
#      - $COMPILE_ROOT/rtl/prim_assert_dummy_macros.svh
      - $COMPILE_ROOT/rtl/prim_count.sv
#      - $COMPILE_ROOT/rtl/prim_assert_yosys_macros.svh
      - $COMPILE_ROOT/rtl/prim_sparse_fsm_flop.sv
      - $COMPILE_ROOT/rtl/prim_dom_and_2share.sv
      - $COMPILE_ROOT/rtl/prim_sec_anchor_flop.sv
      - $COMPILE_ROOT/rtl/prim_reg_we_check.sv
      - $COMPILE_ROOT/rtl/prim_packer_fifo.sv
      - $COMPILE_ROOT/rtl/prim_max_tree.sv
      - $COMPILE_ROOT/rtl/prim_subreg_arb.sv
      - $COMPILE_ROOT/rtl/prim_subreg.sv
      - $COMPILE_ROOT/rtl/prim_intr_hw.sv
      - $COMPILE_ROOT/rtl/prim_onehot_check.sv
      - $COMPILE_ROOT/rtl/prim_mubi8_sync.sv
      - $COMPILE_ROOT/rtl/prim_fifo_sync_cnt.sv
      - $COMPILE_ROOT/rtl/prim_buf.sv
      - $COMPILE_ROOT/rtl/prim_lc_sync.sv
      - $COMPILE_ROOT/rtl/prim_alert_receiver.sv
#      - $COMPILE_ROOT/rtl/prim_assert_standard_macros.svh
      - $COMPILE_ROOT/rtl/prim_flop.sv
      - $COMPILE_ROOT/rtl/prim_alert_sender.sv
      - $COMPILE_ROOT/rtl/prim_fifo_sync.sv
      - $COMPILE_ROOT/rtl/prim_arbiter_ppc.sv
#      - $COMPILE_ROOT/rtl/prim_assert.sv
#      - $COMPILE_ROOT/rtl/prim_assert_sec_cm.svh
      - $COMPILE_ROOT/rtl/prim_sum_tree.sv
      - $COMPILE_ROOT/rtl/prim_subreg_ext.sv
      - $COMPILE_ROOT/rtl/prim_edge_detector.sv
    tops: [prim]
