---
provides: [sha3_ctrl]
schema_version: 2.4.0
requires:
  - libs
  - caliptra_prim
  - caliptra_tlul_pkg
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/ot_sha3_pkg.sv
      - $COMPILE_ROOT/rtl/kmac_pkg.sv
      - $COMPILE_ROOT/rtl/kmac_reg_pkg.sv
      - $COMPILE_ROOT/rtl/sha3_reg_pkg.sv
      - $COMPILE_ROOT/rtl/ot_keccak_2share.sv
      - $COMPILE_ROOT/rtl/ot_keccak_round.sv
      - $COMPILE_ROOT/rtl/kmac_app.sv
      - $COMPILE_ROOT/rtl/kmac_core.sv
      - $COMPILE_ROOT/rtl/kmac_entropy.sv
      - $COMPILE_ROOT/rtl/kmac_errchk.sv
      - $COMPILE_ROOT/rtl/kmac_msgfifo.sv
      - $COMPILE_ROOT/rtl/kmac_reg_top.sv
      - $COMPILE_ROOT/rtl/kmac_staterd.sv
      - $COMPILE_ROOT/rtl/kmac.sv
      - $COMPILE_ROOT/rtl/ot_sha3pad.sv
      - $COMPILE_ROOT/rtl/sha3_reg.sv
      - $COMPILE_ROOT/rtl/ot_sha3.sv
      - $COMPILE_ROOT/rtl/sha3_ctrl.sv
    tops: [sha3_ctrl]
  rtl_lint:
    directories: []
    waiver_files:
      - $MSFT_REPO_ROOT/src/sha3/config/design_lint/sglint_waivers
