
// This file was autogenerated by PeakRDL-uvm
package hmac256_reg_uvm;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    `include "hmac256_reg_covergroups.svh"
    // Reg - hmac256_reg::HMAC256_NAME
    class hmac256_reg__HMAC256_NAME extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__HMAC256_NAME_bit_cg NAME_bit_cg[32];
        hmac256_reg__HMAC256_NAME_fld_cg fld_cg;
        rand uvm_reg_field NAME;

        function new(string name = "hmac256_reg__HMAC256_NAME");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.NAME = new("NAME");
            this.NAME.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(NAME_bit_cg[bt]) NAME_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__HMAC256_NAME

    // Reg - hmac256_reg::HMAC256_VERSION
    class hmac256_reg__HMAC256_VERSION extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__HMAC256_VERSION_bit_cg VERSION_bit_cg[32];
        hmac256_reg__HMAC256_VERSION_fld_cg fld_cg;
        rand uvm_reg_field VERSION;

        function new(string name = "hmac256_reg__HMAC256_VERSION");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.VERSION = new("VERSION");
            this.VERSION.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(VERSION_bit_cg[bt]) VERSION_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__HMAC256_VERSION

    // Reg - hmac256_reg::HMAC256_CTRL
    class hmac256_reg__HMAC256_CTRL extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__HMAC256_CTRL_bit_cg INIT_bit_cg[1];
        hmac256_reg__HMAC256_CTRL_bit_cg NEXT_bit_cg[1];
        hmac256_reg__HMAC256_CTRL_bit_cg ZEROIZE_bit_cg[1];
        hmac256_reg__HMAC256_CTRL_bit_cg MODE_bit_cg[1];
        hmac256_reg__HMAC256_CTRL_bit_cg Reserved4_bit_cg[1];
        hmac256_reg__HMAC256_CTRL_bit_cg LAST_bit_cg[1];
        hmac256_reg__HMAC256_CTRL_bit_cg Reserved6_bit_cg[1];
        hmac256_reg__HMAC256_CTRL_bit_cg RESTORE_bit_cg[1];
        hmac256_reg__HMAC256_CTRL_fld_cg fld_cg;
        rand uvm_reg_field INIT;
        rand uvm_reg_field NEXT;
        rand uvm_reg_field ZEROIZE;
        rand uvm_reg_field MODE;
        rand uvm_reg_field Reserved4;
        rand uvm_reg_field LAST;
        rand uvm_reg_field Reserved6;
        rand uvm_reg_field RESTORE;

        function new(string name = "hmac256_reg__HMAC256_CTRL");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.INIT = new("INIT");
            this.INIT.configure(this, 1, 0, "WO", 0, 'h0, 1, 1, 0);
            this.NEXT = new("NEXT");
            this.NEXT.configure(this, 1, 1, "WO", 0, 'h0, 1, 1, 0);
            this.ZEROIZE = new("ZEROIZE");
            this.ZEROIZE.configure(this, 1, 2, "WO", 0, 'h0, 1, 1, 0);
            this.MODE = new("MODE");
            this.MODE.configure(this, 1, 3, "WO", 0, 'h1, 1, 1, 0);
            this.Reserved4 = new("Reserved4");
            this.Reserved4.configure(this, 1, 4, "WO", 0, 'h0, 1, 1, 0);
            this.LAST = new("LAST");
            this.LAST.configure(this, 1, 5, "WO", 0, 'h0, 1, 1, 0);
            this.Reserved6 = new("Reserved6");
            this.Reserved6.configure(this, 1, 6, "WO", 0, 'h0, 1, 1, 0);
            this.RESTORE = new("RESTORE");
            this.RESTORE.configure(this, 1, 7, "WO", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(INIT_bit_cg[bt]) INIT_bit_cg[bt] = new();
                foreach(NEXT_bit_cg[bt]) NEXT_bit_cg[bt] = new();
                foreach(ZEROIZE_bit_cg[bt]) ZEROIZE_bit_cg[bt] = new();
                foreach(MODE_bit_cg[bt]) MODE_bit_cg[bt] = new();
                foreach(Reserved4_bit_cg[bt]) Reserved4_bit_cg[bt] = new();
                foreach(LAST_bit_cg[bt]) LAST_bit_cg[bt] = new();
                foreach(Reserved6_bit_cg[bt]) Reserved6_bit_cg[bt] = new();
                foreach(RESTORE_bit_cg[bt]) RESTORE_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__HMAC256_CTRL

    // Reg - hmac256_reg::HMAC256_STATUS
    class hmac256_reg__HMAC256_STATUS extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__HMAC256_STATUS_bit_cg READY_bit_cg[1];
        hmac256_reg__HMAC256_STATUS_bit_cg VALID_bit_cg[1];
        hmac256_reg__HMAC256_STATUS_fld_cg fld_cg;
        rand uvm_reg_field READY;
        rand uvm_reg_field VALID;

        function new(string name = "hmac256_reg__HMAC256_STATUS");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.READY = new("READY");
            this.READY.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.VALID = new("VALID");
            this.VALID.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(READY_bit_cg[bt]) READY_bit_cg[bt] = new();
                foreach(VALID_bit_cg[bt]) VALID_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__HMAC256_STATUS

    // Reg - hmac256_reg::HMAC256_KEY
    class hmac256_reg__HMAC256_KEY extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__HMAC256_KEY_bit_cg KEY_bit_cg[32];
        hmac256_reg__HMAC256_KEY_fld_cg fld_cg;
        rand uvm_reg_field KEY;

        function new(string name = "hmac256_reg__HMAC256_KEY");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.KEY = new("KEY");
            this.KEY.configure(this, 32, 0, "WO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(KEY_bit_cg[bt]) KEY_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__HMAC256_KEY

    // Reg - hmac256_reg::HMAC256_BLOCK
    class hmac256_reg__HMAC256_BLOCK extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__HMAC256_BLOCK_bit_cg BLOCK_bit_cg[32];
        hmac256_reg__HMAC256_BLOCK_fld_cg fld_cg;
        rand uvm_reg_field BLOCK;

        function new(string name = "hmac256_reg__HMAC256_BLOCK");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.BLOCK = new("BLOCK");
            this.BLOCK.configure(this, 32, 0, "WO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(BLOCK_bit_cg[bt]) BLOCK_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__HMAC256_BLOCK

    // Reg - hmac256_reg::HMAC256_TAG
    class hmac256_reg__HMAC256_TAG extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__HMAC256_TAG_bit_cg TAG_bit_cg[32];
        hmac256_reg__HMAC256_TAG_fld_cg fld_cg;
        rand uvm_reg_field TAG;

        function new(string name = "hmac256_reg__HMAC256_TAG");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.TAG = new("TAG");
            this.TAG.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(TAG_bit_cg[bt]) TAG_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__HMAC256_TAG

    // Reg - hmac256_reg::HMAC256_LFSR_SEED
    class hmac256_reg__HMAC256_LFSR_SEED extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__HMAC256_LFSR_SEED_bit_cg LFSR_SEED_bit_cg[32];
        hmac256_reg__HMAC256_LFSR_SEED_fld_cg fld_cg;
        rand uvm_reg_field LFSR_SEED;

        function new(string name = "hmac256_reg__HMAC256_LFSR_SEED");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.LFSR_SEED = new("LFSR_SEED");
            this.LFSR_SEED.configure(this, 32, 0, "WO", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(LFSR_SEED_bit_cg[bt]) LFSR_SEED_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__HMAC256_LFSR_SEED

    // Reg - hmac256_reg::global_intr_en_t
    class hmac256_reg__global_intr_en_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__global_intr_en_t_bit_cg error_en_bit_cg[1];
        hmac256_reg__global_intr_en_t_bit_cg notif_en_bit_cg[1];
        hmac256_reg__global_intr_en_t_fld_cg fld_cg;
        rand uvm_reg_field error_en;
        rand uvm_reg_field notif_en;

        function new(string name = "hmac256_reg__global_intr_en_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.error_en = new("error_en");
            this.error_en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.notif_en = new("notif_en");
            this.notif_en.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(error_en_bit_cg[bt]) error_en_bit_cg[bt] = new();
                foreach(notif_en_bit_cg[bt]) notif_en_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__global_intr_en_t

    // Reg - hmac256_reg::error_intr_en_t
    class hmac256_reg__error_intr_en_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__error_intr_en_t_bit_cg error0_en_bit_cg[1];
        hmac256_reg__error_intr_en_t_bit_cg error1_en_bit_cg[1];
        hmac256_reg__error_intr_en_t_bit_cg error2_en_bit_cg[1];
        hmac256_reg__error_intr_en_t_bit_cg error3_en_bit_cg[1];
        hmac256_reg__error_intr_en_t_fld_cg fld_cg;
        rand uvm_reg_field error0_en;
        rand uvm_reg_field error1_en;
        rand uvm_reg_field error2_en;
        rand uvm_reg_field error3_en;

        function new(string name = "hmac256_reg__error_intr_en_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.error0_en = new("error0_en");
            this.error0_en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.error1_en = new("error1_en");
            this.error1_en.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            this.error2_en = new("error2_en");
            this.error2_en.configure(this, 1, 2, "RW", 0, 'h0, 1, 1, 0);
            this.error3_en = new("error3_en");
            this.error3_en.configure(this, 1, 3, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(error0_en_bit_cg[bt]) error0_en_bit_cg[bt] = new();
                foreach(error1_en_bit_cg[bt]) error1_en_bit_cg[bt] = new();
                foreach(error2_en_bit_cg[bt]) error2_en_bit_cg[bt] = new();
                foreach(error3_en_bit_cg[bt]) error3_en_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__error_intr_en_t

    // Reg - hmac256_reg::notif_intr_en_t
    class hmac256_reg__notif_intr_en_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__notif_intr_en_t_bit_cg notif_cmd_done_en_bit_cg[1];
        hmac256_reg__notif_intr_en_t_fld_cg fld_cg;
        rand uvm_reg_field notif_cmd_done_en;

        function new(string name = "hmac256_reg__notif_intr_en_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.notif_cmd_done_en = new("notif_cmd_done_en");
            this.notif_cmd_done_en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(notif_cmd_done_en_bit_cg[bt]) notif_cmd_done_en_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__notif_intr_en_t

    // Reg - hmac256_reg::global_intr_t_agg_sts_dd3dcf0a
    class hmac256_reg__global_intr_t_agg_sts_dd3dcf0a extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__global_intr_t_agg_sts_dd3dcf0a_bit_cg agg_sts_bit_cg[1];
        hmac256_reg__global_intr_t_agg_sts_dd3dcf0a_fld_cg fld_cg;
        rand uvm_reg_field agg_sts;

        function new(string name = "hmac256_reg__global_intr_t_agg_sts_dd3dcf0a");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.agg_sts = new("agg_sts");
            this.agg_sts.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(agg_sts_bit_cg[bt]) agg_sts_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__global_intr_t_agg_sts_dd3dcf0a

    // Reg - hmac256_reg::global_intr_t_agg_sts_e6399b4a
    class hmac256_reg__global_intr_t_agg_sts_e6399b4a extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__global_intr_t_agg_sts_e6399b4a_bit_cg agg_sts_bit_cg[1];
        hmac256_reg__global_intr_t_agg_sts_e6399b4a_fld_cg fld_cg;
        rand uvm_reg_field agg_sts;

        function new(string name = "hmac256_reg__global_intr_t_agg_sts_e6399b4a");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.agg_sts = new("agg_sts");
            this.agg_sts.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(agg_sts_bit_cg[bt]) agg_sts_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__global_intr_t_agg_sts_e6399b4a

    // Reg - hmac256_reg::error_intr_t_error0_sts_28545624_error1_sts_40e0d3e1_error2_sts_b1cf2205_error3_sts_74a35378
    class hmac256_reg__error_intr_t_error0_sts_28545624_error1_sts_40e0d3e1_error2_sts_b1cf2205_error3_sts_74a35378 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__error_intr_t_error0_sts_28545624_error1_sts_40e0d3e1_error2_sts_b1cf2205_error3_sts_74a35378_bit_cg error0_sts_bit_cg[1];
        hmac256_reg__error_intr_t_error0_sts_28545624_error1_sts_40e0d3e1_error2_sts_b1cf2205_error3_sts_74a35378_bit_cg error1_sts_bit_cg[1];
        hmac256_reg__error_intr_t_error0_sts_28545624_error1_sts_40e0d3e1_error2_sts_b1cf2205_error3_sts_74a35378_bit_cg error2_sts_bit_cg[1];
        hmac256_reg__error_intr_t_error0_sts_28545624_error1_sts_40e0d3e1_error2_sts_b1cf2205_error3_sts_74a35378_bit_cg error3_sts_bit_cg[1];
        hmac256_reg__error_intr_t_error0_sts_28545624_error1_sts_40e0d3e1_error2_sts_b1cf2205_error3_sts_74a35378_fld_cg fld_cg;
        rand uvm_reg_field error0_sts;
        rand uvm_reg_field error1_sts;
        rand uvm_reg_field error2_sts;
        rand uvm_reg_field error3_sts;

        function new(string name = "hmac256_reg__error_intr_t_error0_sts_28545624_error1_sts_40e0d3e1_error2_sts_b1cf2205_error3_sts_74a35378");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.error0_sts = new("error0_sts");
            this.error0_sts.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            this.error1_sts = new("error1_sts");
            this.error1_sts.configure(this, 1, 1, "W1C", 1, 'h0, 1, 1, 0);
            this.error2_sts = new("error2_sts");
            this.error2_sts.configure(this, 1, 2, "W1C", 1, 'h0, 1, 1, 0);
            this.error3_sts = new("error3_sts");
            this.error3_sts.configure(this, 1, 3, "W1C", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(error0_sts_bit_cg[bt]) error0_sts_bit_cg[bt] = new();
                foreach(error1_sts_bit_cg[bt]) error1_sts_bit_cg[bt] = new();
                foreach(error2_sts_bit_cg[bt]) error2_sts_bit_cg[bt] = new();
                foreach(error3_sts_bit_cg[bt]) error3_sts_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__error_intr_t_error0_sts_28545624_error1_sts_40e0d3e1_error2_sts_b1cf2205_error3_sts_74a35378

    // Reg - hmac256_reg::notif_intr_t_notif_cmd_done_sts_1c68637e
    class hmac256_reg__notif_intr_t_notif_cmd_done_sts_1c68637e extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__notif_intr_t_notif_cmd_done_sts_1c68637e_bit_cg notif_cmd_done_sts_bit_cg[1];
        hmac256_reg__notif_intr_t_notif_cmd_done_sts_1c68637e_fld_cg fld_cg;
        rand uvm_reg_field notif_cmd_done_sts;

        function new(string name = "hmac256_reg__notif_intr_t_notif_cmd_done_sts_1c68637e");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.notif_cmd_done_sts = new("notif_cmd_done_sts");
            this.notif_cmd_done_sts.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(notif_cmd_done_sts_bit_cg[bt]) notif_cmd_done_sts_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__notif_intr_t_notif_cmd_done_sts_1c68637e

    // Reg - hmac256_reg::error_intr_trig_t
    class hmac256_reg__error_intr_trig_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__error_intr_trig_t_bit_cg error0_trig_bit_cg[1];
        hmac256_reg__error_intr_trig_t_bit_cg error1_trig_bit_cg[1];
        hmac256_reg__error_intr_trig_t_bit_cg error2_trig_bit_cg[1];
        hmac256_reg__error_intr_trig_t_bit_cg error3_trig_bit_cg[1];
        hmac256_reg__error_intr_trig_t_fld_cg fld_cg;
        rand uvm_reg_field error0_trig;
        rand uvm_reg_field error1_trig;
        rand uvm_reg_field error2_trig;
        rand uvm_reg_field error3_trig;

        function new(string name = "hmac256_reg__error_intr_trig_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.error0_trig = new("error0_trig");
            this.error0_trig.configure(this, 1, 0, "W1S", 0, 'h0, 1, 1, 0);
            this.error1_trig = new("error1_trig");
            this.error1_trig.configure(this, 1, 1, "W1S", 0, 'h0, 1, 1, 0);
            this.error2_trig = new("error2_trig");
            this.error2_trig.configure(this, 1, 2, "W1S", 0, 'h0, 1, 1, 0);
            this.error3_trig = new("error3_trig");
            this.error3_trig.configure(this, 1, 3, "W1S", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(error0_trig_bit_cg[bt]) error0_trig_bit_cg[bt] = new();
                foreach(error1_trig_bit_cg[bt]) error1_trig_bit_cg[bt] = new();
                foreach(error2_trig_bit_cg[bt]) error2_trig_bit_cg[bt] = new();
                foreach(error3_trig_bit_cg[bt]) error3_trig_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__error_intr_trig_t

    // Reg - hmac256_reg::notif_intr_trig_t
    class hmac256_reg__notif_intr_trig_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__notif_intr_trig_t_bit_cg notif_cmd_done_trig_bit_cg[1];
        hmac256_reg__notif_intr_trig_t_fld_cg fld_cg;
        rand uvm_reg_field notif_cmd_done_trig;

        function new(string name = "hmac256_reg__notif_intr_trig_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.notif_cmd_done_trig = new("notif_cmd_done_trig");
            this.notif_cmd_done_trig.configure(this, 1, 0, "W1S", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(notif_cmd_done_trig_bit_cg[bt]) notif_cmd_done_trig_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__notif_intr_trig_t

    // Reg - hmac256_reg::intr_count_t_cnt_35ace267
    class hmac256_reg__intr_count_t_cnt_35ace267 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__intr_count_t_cnt_35ace267_bit_cg cnt_bit_cg[32];
        hmac256_reg__intr_count_t_cnt_35ace267_fld_cg fld_cg;
        rand uvm_reg_field cnt;

        function new(string name = "hmac256_reg__intr_count_t_cnt_35ace267");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.cnt = new("cnt");
            this.cnt.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(cnt_bit_cg[bt]) cnt_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__intr_count_t_cnt_35ace267

    // Reg - hmac256_reg::intr_count_t_cnt_73c42c28
    class hmac256_reg__intr_count_t_cnt_73c42c28 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__intr_count_t_cnt_73c42c28_bit_cg cnt_bit_cg[32];
        hmac256_reg__intr_count_t_cnt_73c42c28_fld_cg fld_cg;
        rand uvm_reg_field cnt;

        function new(string name = "hmac256_reg__intr_count_t_cnt_73c42c28");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.cnt = new("cnt");
            this.cnt.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(cnt_bit_cg[bt]) cnt_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__intr_count_t_cnt_73c42c28

    // Reg - hmac256_reg::intr_count_t_cnt_d8af96ff
    class hmac256_reg__intr_count_t_cnt_d8af96ff extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__intr_count_t_cnt_d8af96ff_bit_cg cnt_bit_cg[32];
        hmac256_reg__intr_count_t_cnt_d8af96ff_fld_cg fld_cg;
        rand uvm_reg_field cnt;

        function new(string name = "hmac256_reg__intr_count_t_cnt_d8af96ff");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.cnt = new("cnt");
            this.cnt.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(cnt_bit_cg[bt]) cnt_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__intr_count_t_cnt_d8af96ff

    // Reg - hmac256_reg::intr_count_t_cnt_9bd7f809
    class hmac256_reg__intr_count_t_cnt_9bd7f809 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__intr_count_t_cnt_9bd7f809_bit_cg cnt_bit_cg[32];
        hmac256_reg__intr_count_t_cnt_9bd7f809_fld_cg fld_cg;
        rand uvm_reg_field cnt;

        function new(string name = "hmac256_reg__intr_count_t_cnt_9bd7f809");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.cnt = new("cnt");
            this.cnt.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(cnt_bit_cg[bt]) cnt_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__intr_count_t_cnt_9bd7f809

    // Reg - hmac256_reg::intr_count_t_cnt_be67d6d5
    class hmac256_reg__intr_count_t_cnt_be67d6d5 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__intr_count_t_cnt_be67d6d5_bit_cg cnt_bit_cg[32];
        hmac256_reg__intr_count_t_cnt_be67d6d5_fld_cg fld_cg;
        rand uvm_reg_field cnt;

        function new(string name = "hmac256_reg__intr_count_t_cnt_be67d6d5");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.cnt = new("cnt");
            this.cnt.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(cnt_bit_cg[bt]) cnt_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__intr_count_t_cnt_be67d6d5

    // Reg - hmac256_reg::intr_count_incr_t_pulse_37026c97
    class hmac256_reg__intr_count_incr_t_pulse_37026c97 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__intr_count_incr_t_pulse_37026c97_bit_cg pulse_bit_cg[1];
        hmac256_reg__intr_count_incr_t_pulse_37026c97_fld_cg fld_cg;
        rand uvm_reg_field pulse;

        function new(string name = "hmac256_reg__intr_count_incr_t_pulse_37026c97");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.pulse = new("pulse");
            this.pulse.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(pulse_bit_cg[bt]) pulse_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__intr_count_incr_t_pulse_37026c97

    // Reg - hmac256_reg::intr_count_incr_t_pulse_d860d977
    class hmac256_reg__intr_count_incr_t_pulse_d860d977 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__intr_count_incr_t_pulse_d860d977_bit_cg pulse_bit_cg[1];
        hmac256_reg__intr_count_incr_t_pulse_d860d977_fld_cg fld_cg;
        rand uvm_reg_field pulse;

        function new(string name = "hmac256_reg__intr_count_incr_t_pulse_d860d977");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.pulse = new("pulse");
            this.pulse.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(pulse_bit_cg[bt]) pulse_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__intr_count_incr_t_pulse_d860d977

    // Reg - hmac256_reg::intr_count_incr_t_pulse_87b45fe7
    class hmac256_reg__intr_count_incr_t_pulse_87b45fe7 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__intr_count_incr_t_pulse_87b45fe7_bit_cg pulse_bit_cg[1];
        hmac256_reg__intr_count_incr_t_pulse_87b45fe7_fld_cg fld_cg;
        rand uvm_reg_field pulse;

        function new(string name = "hmac256_reg__intr_count_incr_t_pulse_87b45fe7");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.pulse = new("pulse");
            this.pulse.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(pulse_bit_cg[bt]) pulse_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__intr_count_incr_t_pulse_87b45fe7

    // Reg - hmac256_reg::intr_count_incr_t_pulse_c1689ee6
    class hmac256_reg__intr_count_incr_t_pulse_c1689ee6 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__intr_count_incr_t_pulse_c1689ee6_bit_cg pulse_bit_cg[1];
        hmac256_reg__intr_count_incr_t_pulse_c1689ee6_fld_cg fld_cg;
        rand uvm_reg_field pulse;

        function new(string name = "hmac256_reg__intr_count_incr_t_pulse_c1689ee6");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.pulse = new("pulse");
            this.pulse.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(pulse_bit_cg[bt]) pulse_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__intr_count_incr_t_pulse_c1689ee6

    // Reg - hmac256_reg::intr_count_incr_t_pulse_6173128e
    class hmac256_reg__intr_count_incr_t_pulse_6173128e extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        hmac256_reg__intr_count_incr_t_pulse_6173128e_bit_cg pulse_bit_cg[1];
        hmac256_reg__intr_count_incr_t_pulse_6173128e_fld_cg fld_cg;
        rand uvm_reg_field pulse;

        function new(string name = "hmac256_reg__intr_count_incr_t_pulse_6173128e");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.pulse = new("pulse");
            this.pulse.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(pulse_bit_cg[bt]) pulse_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : hmac256_reg__intr_count_incr_t_pulse_6173128e

    // Regfile - hmac256_reg::intr_block_t
    class hmac256_reg__intr_block_t extends uvm_reg_block;
        rand hmac256_reg__global_intr_en_t global_intr_en_r;
        rand hmac256_reg__error_intr_en_t error_intr_en_r;
        rand hmac256_reg__notif_intr_en_t notif_intr_en_r;
        rand hmac256_reg__global_intr_t_agg_sts_dd3dcf0a error_global_intr_r;
        rand hmac256_reg__global_intr_t_agg_sts_e6399b4a notif_global_intr_r;
        rand hmac256_reg__error_intr_t_error0_sts_28545624_error1_sts_40e0d3e1_error2_sts_b1cf2205_error3_sts_74a35378 error_internal_intr_r;
        rand hmac256_reg__notif_intr_t_notif_cmd_done_sts_1c68637e notif_internal_intr_r;
        rand hmac256_reg__error_intr_trig_t error_intr_trig_r;
        rand hmac256_reg__notif_intr_trig_t notif_intr_trig_r;
        rand hmac256_reg__intr_count_t_cnt_35ace267 error0_intr_count_r;
        rand hmac256_reg__intr_count_t_cnt_73c42c28 error1_intr_count_r;
        rand hmac256_reg__intr_count_t_cnt_d8af96ff error2_intr_count_r;
        rand hmac256_reg__intr_count_t_cnt_9bd7f809 error3_intr_count_r;
        rand hmac256_reg__intr_count_t_cnt_be67d6d5 notif_cmd_done_intr_count_r;
        rand hmac256_reg__intr_count_incr_t_pulse_37026c97 error0_intr_count_incr_r;
        rand hmac256_reg__intr_count_incr_t_pulse_d860d977 error1_intr_count_incr_r;
        rand hmac256_reg__intr_count_incr_t_pulse_87b45fe7 error2_intr_count_incr_r;
        rand hmac256_reg__intr_count_incr_t_pulse_c1689ee6 error3_intr_count_incr_r;
        rand hmac256_reg__intr_count_incr_t_pulse_6173128e notif_cmd_done_intr_count_incr_r;

        function new(string name = "hmac256_reg__intr_block_t");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.global_intr_en_r = new("global_intr_en_r");
            this.global_intr_en_r.configure(this);

            this.global_intr_en_r.build();
            this.default_map.add_reg(this.global_intr_en_r, 'h0);
            this.error_intr_en_r = new("error_intr_en_r");
            this.error_intr_en_r.configure(this);

            this.error_intr_en_r.build();
            this.default_map.add_reg(this.error_intr_en_r, 'h4);
            this.notif_intr_en_r = new("notif_intr_en_r");
            this.notif_intr_en_r.configure(this);

            this.notif_intr_en_r.build();
            this.default_map.add_reg(this.notif_intr_en_r, 'h8);
            this.error_global_intr_r = new("error_global_intr_r");
            this.error_global_intr_r.configure(this);

            this.error_global_intr_r.build();
            this.default_map.add_reg(this.error_global_intr_r, 'hc);
            this.notif_global_intr_r = new("notif_global_intr_r");
            this.notif_global_intr_r.configure(this);

            this.notif_global_intr_r.build();
            this.default_map.add_reg(this.notif_global_intr_r, 'h10);
            this.error_internal_intr_r = new("error_internal_intr_r");
            this.error_internal_intr_r.configure(this);

            this.error_internal_intr_r.build();
            this.default_map.add_reg(this.error_internal_intr_r, 'h14);
            this.notif_internal_intr_r = new("notif_internal_intr_r");
            this.notif_internal_intr_r.configure(this);

            this.notif_internal_intr_r.build();
            this.default_map.add_reg(this.notif_internal_intr_r, 'h18);
            this.error_intr_trig_r = new("error_intr_trig_r");
            this.error_intr_trig_r.configure(this);

            this.error_intr_trig_r.build();
            this.default_map.add_reg(this.error_intr_trig_r, 'h1c);
            this.notif_intr_trig_r = new("notif_intr_trig_r");
            this.notif_intr_trig_r.configure(this);

            this.notif_intr_trig_r.build();
            this.default_map.add_reg(this.notif_intr_trig_r, 'h20);
            this.error0_intr_count_r = new("error0_intr_count_r");
            this.error0_intr_count_r.configure(this);

            this.error0_intr_count_r.build();
            this.default_map.add_reg(this.error0_intr_count_r, 'h100);
            this.error1_intr_count_r = new("error1_intr_count_r");
            this.error1_intr_count_r.configure(this);

            this.error1_intr_count_r.build();
            this.default_map.add_reg(this.error1_intr_count_r, 'h104);
            this.error2_intr_count_r = new("error2_intr_count_r");
            this.error2_intr_count_r.configure(this);

            this.error2_intr_count_r.build();
            this.default_map.add_reg(this.error2_intr_count_r, 'h108);
            this.error3_intr_count_r = new("error3_intr_count_r");
            this.error3_intr_count_r.configure(this);

            this.error3_intr_count_r.build();
            this.default_map.add_reg(this.error3_intr_count_r, 'h10c);
            this.notif_cmd_done_intr_count_r = new("notif_cmd_done_intr_count_r");
            this.notif_cmd_done_intr_count_r.configure(this);

            this.notif_cmd_done_intr_count_r.build();
            this.default_map.add_reg(this.notif_cmd_done_intr_count_r, 'h180);
            this.error0_intr_count_incr_r = new("error0_intr_count_incr_r");
            this.error0_intr_count_incr_r.configure(this);

            this.error0_intr_count_incr_r.build();
            this.default_map.add_reg(this.error0_intr_count_incr_r, 'h200);
            this.error1_intr_count_incr_r = new("error1_intr_count_incr_r");
            this.error1_intr_count_incr_r.configure(this);

            this.error1_intr_count_incr_r.build();
            this.default_map.add_reg(this.error1_intr_count_incr_r, 'h204);
            this.error2_intr_count_incr_r = new("error2_intr_count_incr_r");
            this.error2_intr_count_incr_r.configure(this);

            this.error2_intr_count_incr_r.build();
            this.default_map.add_reg(this.error2_intr_count_incr_r, 'h208);
            this.error3_intr_count_incr_r = new("error3_intr_count_incr_r");
            this.error3_intr_count_incr_r.configure(this);

            this.error3_intr_count_incr_r.build();
            this.default_map.add_reg(this.error3_intr_count_incr_r, 'h20c);
            this.notif_cmd_done_intr_count_incr_r = new("notif_cmd_done_intr_count_incr_r");
            this.notif_cmd_done_intr_count_incr_r.configure(this);

            this.notif_cmd_done_intr_count_incr_r.build();
            this.default_map.add_reg(this.notif_cmd_done_intr_count_incr_r, 'h210);
        endfunction : build
    endclass : hmac256_reg__intr_block_t

    // Addrmap - hmac256_reg
    class hmac256_reg extends uvm_reg_block;
        rand hmac256_reg__HMAC256_NAME HMAC256_NAME[2];
        rand hmac256_reg__HMAC256_VERSION HMAC256_VERSION[2];
        rand hmac256_reg__HMAC256_CTRL HMAC256_CTRL;
        rand hmac256_reg__HMAC256_STATUS HMAC256_STATUS;
        rand hmac256_reg__HMAC256_KEY HMAC256_KEY[16];
        rand hmac256_reg__HMAC256_BLOCK HMAC256_BLOCK[16];
        rand hmac256_reg__HMAC256_TAG HMAC256_TAG[8];
        rand hmac256_reg__HMAC256_LFSR_SEED HMAC256_LFSR_SEED[6];
        rand hmac256_reg__intr_block_t intr_block_rf;

        function new(string name = "hmac256_reg");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            foreach(this.HMAC256_NAME[i0]) begin
                this.HMAC256_NAME[i0] = new($sformatf("HMAC256_NAME[%0d]", i0));
                this.HMAC256_NAME[i0].configure(this);
                
                this.HMAC256_NAME[i0].build();
                this.default_map.add_reg(this.HMAC256_NAME[i0], 'h0 + i0*'h4);
            end
            foreach(this.HMAC256_VERSION[i0]) begin
                this.HMAC256_VERSION[i0] = new($sformatf("HMAC256_VERSION[%0d]", i0));
                this.HMAC256_VERSION[i0].configure(this);
                
                this.HMAC256_VERSION[i0].build();
                this.default_map.add_reg(this.HMAC256_VERSION[i0], 'h8 + i0*'h4);
            end
            this.HMAC256_CTRL = new("HMAC256_CTRL");
            this.HMAC256_CTRL.configure(this);

            this.HMAC256_CTRL.build();
            this.default_map.add_reg(this.HMAC256_CTRL, 'h10);
            this.HMAC256_STATUS = new("HMAC256_STATUS");
            this.HMAC256_STATUS.configure(this);

            this.HMAC256_STATUS.build();
            this.default_map.add_reg(this.HMAC256_STATUS, 'h18);
            foreach(this.HMAC256_KEY[i0]) begin
                this.HMAC256_KEY[i0] = new($sformatf("HMAC256_KEY[%0d]", i0));
                this.HMAC256_KEY[i0].configure(this);
                
                this.HMAC256_KEY[i0].build();
                this.default_map.add_reg(this.HMAC256_KEY[i0], 'h40 + i0*'h4);
            end
            foreach(this.HMAC256_BLOCK[i0]) begin
                this.HMAC256_BLOCK[i0] = new($sformatf("HMAC256_BLOCK[%0d]", i0));
                this.HMAC256_BLOCK[i0].configure(this);
                
                this.HMAC256_BLOCK[i0].build();
                this.default_map.add_reg(this.HMAC256_BLOCK[i0], 'h80 + i0*'h4);
            end
            foreach(this.HMAC256_TAG[i0]) begin
                this.HMAC256_TAG[i0] = new($sformatf("HMAC256_TAG[%0d]", i0));
                this.HMAC256_TAG[i0].configure(this);
                
                this.HMAC256_TAG[i0].build();
                this.default_map.add_reg(this.HMAC256_TAG[i0], 'hc0 + i0*'h4);
            end
            foreach(this.HMAC256_LFSR_SEED[i0]) begin
                this.HMAC256_LFSR_SEED[i0] = new($sformatf("HMAC256_LFSR_SEED[%0d]", i0));
                this.HMAC256_LFSR_SEED[i0].configure(this);
                
                this.HMAC256_LFSR_SEED[i0].build();
                this.default_map.add_reg(this.HMAC256_LFSR_SEED[i0], 'he0 + i0*'h4);
            end
            this.intr_block_rf = new("intr_block_rf");
            this.intr_block_rf.configure(this);
            this.intr_block_rf.build();
            this.default_map.add_submap(this.intr_block_rf.default_map, 'h800);
        endfunction : build
    endclass : hmac256_reg

    `include "hmac256_reg_sample.svh"
endpackage: hmac256_reg_uvm
