// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef ECC_REG_HEADER
#define ECC_REG_HEADER


#define ECC_REG_ECC_NAME_0                                  (0x0)
#define ECC_REG_ECC_NAME_1                                  (0x4)
#define ECC_REG_ECC_VERSION_0                               (0x8)
#define ECC_REG_ECC_VERSION_1                               (0xc)
#define ECC_REG_ECC_CTRL                                    (0x10)
#define ECC_REG_ECC_STATUS                                  (0x18)
#define ECC_REG_ECC_SEED_0                                  (0x80)
#define ECC_REG_ECC_SEED_1                                  (0x84)
#define ECC_REG_ECC_SEED_2                                  (0x88)
#define ECC_REG_ECC_SEED_3                                  (0x8c)
#define ECC_REG_ECC_SEED_4                                  (0x90)
#define ECC_REG_ECC_SEED_5                                  (0x94)
#define ECC_REG_ECC_SEED_6                                  (0x98)
#define ECC_REG_ECC_SEED_7                                  (0x9c)
#define ECC_REG_ECC_SEED_8                                  (0xa0)
#define ECC_REG_ECC_SEED_9                                  (0xa4)
#define ECC_REG_ECC_SEED_10                                 (0xa8)
#define ECC_REG_ECC_SEED_11                                 (0xac)
#define ECC_REG_ECC_MSG_0                                   (0x100)
#define ECC_REG_ECC_MSG_1                                   (0x104)
#define ECC_REG_ECC_MSG_2                                   (0x108)
#define ECC_REG_ECC_MSG_3                                   (0x10c)
#define ECC_REG_ECC_MSG_4                                   (0x110)
#define ECC_REG_ECC_MSG_5                                   (0x114)
#define ECC_REG_ECC_MSG_6                                   (0x118)
#define ECC_REG_ECC_MSG_7                                   (0x11c)
#define ECC_REG_ECC_MSG_8                                   (0x120)
#define ECC_REG_ECC_MSG_9                                   (0x124)
#define ECC_REG_ECC_MSG_10                                  (0x128)
#define ECC_REG_ECC_MSG_11                                  (0x12c)
#define ECC_REG_ECC_PRIVKEY_0                               (0x180)
#define ECC_REG_ECC_PRIVKEY_1                               (0x184)
#define ECC_REG_ECC_PRIVKEY_2                               (0x188)
#define ECC_REG_ECC_PRIVKEY_3                               (0x18c)
#define ECC_REG_ECC_PRIVKEY_4                               (0x190)
#define ECC_REG_ECC_PRIVKEY_5                               (0x194)
#define ECC_REG_ECC_PRIVKEY_6                               (0x198)
#define ECC_REG_ECC_PRIVKEY_7                               (0x19c)
#define ECC_REG_ECC_PRIVKEY_8                               (0x1a0)
#define ECC_REG_ECC_PRIVKEY_9                               (0x1a4)
#define ECC_REG_ECC_PRIVKEY_10                              (0x1a8)
#define ECC_REG_ECC_PRIVKEY_11                              (0x1ac)
#define ECC_REG_ECC_PUBKEY_X_0                              (0x200)
#define ECC_REG_ECC_PUBKEY_X_1                              (0x204)
#define ECC_REG_ECC_PUBKEY_X_2                              (0x208)
#define ECC_REG_ECC_PUBKEY_X_3                              (0x20c)
#define ECC_REG_ECC_PUBKEY_X_4                              (0x210)
#define ECC_REG_ECC_PUBKEY_X_5                              (0x214)
#define ECC_REG_ECC_PUBKEY_X_6                              (0x218)
#define ECC_REG_ECC_PUBKEY_X_7                              (0x21c)
#define ECC_REG_ECC_PUBKEY_X_8                              (0x220)
#define ECC_REG_ECC_PUBKEY_X_9                              (0x224)
#define ECC_REG_ECC_PUBKEY_X_10                             (0x228)
#define ECC_REG_ECC_PUBKEY_X_11                             (0x22c)
#define ECC_REG_ECC_PUBKEY_Y_0                              (0x280)
#define ECC_REG_ECC_PUBKEY_Y_1                              (0x284)
#define ECC_REG_ECC_PUBKEY_Y_2                              (0x288)
#define ECC_REG_ECC_PUBKEY_Y_3                              (0x28c)
#define ECC_REG_ECC_PUBKEY_Y_4                              (0x290)
#define ECC_REG_ECC_PUBKEY_Y_5                              (0x294)
#define ECC_REG_ECC_PUBKEY_Y_6                              (0x298)
#define ECC_REG_ECC_PUBKEY_Y_7                              (0x29c)
#define ECC_REG_ECC_PUBKEY_Y_8                              (0x2a0)
#define ECC_REG_ECC_PUBKEY_Y_9                              (0x2a4)
#define ECC_REG_ECC_PUBKEY_Y_10                             (0x2a8)
#define ECC_REG_ECC_PUBKEY_Y_11                             (0x2ac)
#define ECC_REG_ECC_R_0                                     (0x300)
#define ECC_REG_ECC_R_1                                     (0x304)
#define ECC_REG_ECC_R_2                                     (0x308)
#define ECC_REG_ECC_R_3                                     (0x30c)
#define ECC_REG_ECC_R_4                                     (0x310)
#define ECC_REG_ECC_R_5                                     (0x314)
#define ECC_REG_ECC_R_6                                     (0x318)
#define ECC_REG_ECC_R_7                                     (0x31c)
#define ECC_REG_ECC_R_8                                     (0x320)
#define ECC_REG_ECC_R_9                                     (0x324)
#define ECC_REG_ECC_R_10                                    (0x328)
#define ECC_REG_ECC_R_11                                    (0x32c)
#define ECC_REG_ECC_S_0                                     (0x380)
#define ECC_REG_ECC_S_1                                     (0x384)
#define ECC_REG_ECC_S_2                                     (0x388)
#define ECC_REG_ECC_S_3                                     (0x38c)
#define ECC_REG_ECC_S_4                                     (0x390)
#define ECC_REG_ECC_S_5                                     (0x394)
#define ECC_REG_ECC_S_6                                     (0x398)
#define ECC_REG_ECC_S_7                                     (0x39c)
#define ECC_REG_ECC_S_8                                     (0x3a0)
#define ECC_REG_ECC_S_9                                     (0x3a4)
#define ECC_REG_ECC_S_10                                    (0x3a8)
#define ECC_REG_ECC_S_11                                    (0x3ac)
#define ECC_REG_ECC_VERIFY_R_0                              (0x400)
#define ECC_REG_ECC_VERIFY_R_1                              (0x404)
#define ECC_REG_ECC_VERIFY_R_2                              (0x408)
#define ECC_REG_ECC_VERIFY_R_3                              (0x40c)
#define ECC_REG_ECC_VERIFY_R_4                              (0x410)
#define ECC_REG_ECC_VERIFY_R_5                              (0x414)
#define ECC_REG_ECC_VERIFY_R_6                              (0x418)
#define ECC_REG_ECC_VERIFY_R_7                              (0x41c)
#define ECC_REG_ECC_VERIFY_R_8                              (0x420)
#define ECC_REG_ECC_VERIFY_R_9                              (0x424)
#define ECC_REG_ECC_VERIFY_R_10                             (0x428)
#define ECC_REG_ECC_VERIFY_R_11                             (0x42c)
#define ECC_REG_ECC_IV_0                                    (0x480)
#define ECC_REG_ECC_IV_1                                    (0x484)
#define ECC_REG_ECC_IV_2                                    (0x488)
#define ECC_REG_ECC_IV_3                                    (0x48c)
#define ECC_REG_ECC_IV_4                                    (0x490)
#define ECC_REG_ECC_IV_5                                    (0x494)
#define ECC_REG_ECC_IV_6                                    (0x498)
#define ECC_REG_ECC_IV_7                                    (0x49c)
#define ECC_REG_ECC_IV_8                                    (0x4a0)
#define ECC_REG_ECC_IV_9                                    (0x4a4)
#define ECC_REG_ECC_IV_10                                   (0x4a8)
#define ECC_REG_ECC_IV_11                                   (0x4ac)


#endif