// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package ecc_reg_pkg;
    typedef struct {
        logic [31:0] next;
    } ecc_reg__ECC_NAME__NAME__in_t;

    typedef struct {
        ecc_reg__ECC_NAME__NAME__in_t NAME;
    } ecc_reg__ECC_NAME__in_t;

    typedef struct {
        logic [31:0] next;
    } ecc_reg__ECC_VERSION__VERSION__in_t;

    typedef struct {
        ecc_reg__ECC_VERSION__VERSION__in_t VERSION;
    } ecc_reg__ECC_VERSION__in_t;

    typedef struct {
        logic [1:0] next;
    } ecc_reg__ECC_CTRL__CTRL__in_t;

    typedef struct {
        ecc_reg__ECC_CTRL__CTRL__in_t CTRL;
    } ecc_reg__ECC_CTRL__in_t;

    typedef struct {
        logic next;
    } ecc_reg__ECC_STATUS__READY__in_t;

    typedef struct {
        logic next;
    } ecc_reg__ECC_STATUS__VALID__in_t;

    typedef struct {
        ecc_reg__ECC_STATUS__READY__in_t READY;
        ecc_reg__ECC_STATUS__VALID__in_t VALID;
    } ecc_reg__ECC_STATUS__in_t;

    typedef struct {
        logic [31:0] next;
    } ecc_reg__ECC_PRIVKEY__PRIVKEY__in_t;

    typedef struct {
        ecc_reg__ECC_PRIVKEY__PRIVKEY__in_t PRIVKEY;
    } ecc_reg__ECC_PRIVKEY__in_t;

    typedef struct {
        logic [31:0] next;
    } ecc_reg__ECC_PUBKEY_X__PUBKEY_X__in_t;

    typedef struct {
        ecc_reg__ECC_PUBKEY_X__PUBKEY_X__in_t PUBKEY_X;
    } ecc_reg__ECC_PUBKEY_X__in_t;

    typedef struct {
        logic [31:0] next;
    } ecc_reg__ECC_PUBKEY_Y__PUBKEY_Y__in_t;

    typedef struct {
        ecc_reg__ECC_PUBKEY_Y__PUBKEY_Y__in_t PUBKEY_Y;
    } ecc_reg__ECC_PUBKEY_Y__in_t;

    typedef struct {
        logic [31:0] next;
    } ecc_reg__ECC_SIGN_R__SIGN_R__in_t;

    typedef struct {
        ecc_reg__ECC_SIGN_R__SIGN_R__in_t SIGN_R;
    } ecc_reg__ECC_SIGN_R__in_t;

    typedef struct {
        logic [31:0] next;
    } ecc_reg__ECC_SIGN_S__SIGN_S__in_t;

    typedef struct {
        ecc_reg__ECC_SIGN_S__SIGN_S__in_t SIGN_S;
    } ecc_reg__ECC_SIGN_S__in_t;

    typedef struct {
        logic [31:0] next;
    } ecc_reg__ECC_VERIFY_R__VERIFY_R__in_t;

    typedef struct {
        ecc_reg__ECC_VERIFY_R__VERIFY_R__in_t VERIFY_R;
    } ecc_reg__ECC_VERIFY_R__in_t;

    typedef struct {
        logic hwset;
    } ecc_reg__intr_block_t__error_intr_t__error_internal_sts_enable_d33001bb_next_52b75ffa_resetsignal_0d7eaa27__in_t;

    typedef struct {
        ecc_reg__intr_block_t__error_intr_t__error_internal_sts_enable_d33001bb_next_52b75ffa_resetsignal_0d7eaa27__in_t error_internal_sts;
    } ecc_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__in_t;

    typedef struct {
        logic hwset;
    } ecc_reg__intr_block_t__notif_intr_t__notif_cmd_done_sts_enable_dabe0b8b_next_540fa3b7__in_t;

    typedef struct {
        ecc_reg__intr_block_t__notif_intr_t__notif_cmd_done_sts_enable_dabe0b8b_next_540fa3b7__in_t notif_cmd_done_sts;
    } ecc_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__in_t;

    typedef struct {
        ecc_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__in_t error_internal_intr_r;
        ecc_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__in_t notif_internal_intr_r;
    } ecc_reg__intr_block_t__in_t;

    typedef struct {
        logic reset_b;
        logic hard_reset_b;
        ecc_reg__ECC_NAME__in_t ECC_NAME[2];
        ecc_reg__ECC_VERSION__in_t ECC_VERSION[2];
        ecc_reg__ECC_CTRL__in_t ECC_CTRL;
        ecc_reg__ECC_STATUS__in_t ECC_STATUS;
        ecc_reg__ECC_PRIVKEY__in_t ECC_PRIVKEY[12];
        ecc_reg__ECC_PUBKEY_X__in_t ECC_PUBKEY_X[12];
        ecc_reg__ECC_PUBKEY_Y__in_t ECC_PUBKEY_Y[12];
        ecc_reg__ECC_SIGN_R__in_t ECC_SIGN_R[12];
        ecc_reg__ECC_SIGN_S__in_t ECC_SIGN_S[12];
        ecc_reg__ECC_VERIFY_R__in_t ECC_VERIFY_R[12];
        ecc_reg__intr_block_t__in_t intr_block_rf;
    } ecc_reg__in_t;

    typedef struct {
        logic [1:0] value;
    } ecc_reg__ECC_CTRL__CTRL__out_t;

    typedef struct {
        ecc_reg__ECC_CTRL__CTRL__out_t CTRL;
    } ecc_reg__ECC_CTRL__out_t;

    typedef struct {
        logic value;
    } ecc_reg__ECC_SCACONFIG__POINT_RND_EN__out_t;

    typedef struct {
        logic value;
    } ecc_reg__ECC_SCACONFIG__MASK_SIGN_EN__out_t;

    typedef struct {
        logic value;
    } ecc_reg__ECC_SCACONFIG__SCALAR_RND_EN__out_t;

    typedef struct {
        logic value;
    } ecc_reg__ECC_SCACONFIG__OPENSSL_EN__out_t;

    typedef struct {
        ecc_reg__ECC_SCACONFIG__POINT_RND_EN__out_t POINT_RND_EN;
        ecc_reg__ECC_SCACONFIG__MASK_SIGN_EN__out_t MASK_SIGN_EN;
        ecc_reg__ECC_SCACONFIG__SCALAR_RND_EN__out_t SCALAR_RND_EN;
        ecc_reg__ECC_SCACONFIG__OPENSSL_EN__out_t OPENSSL_EN;
    } ecc_reg__ECC_SCACONFIG__out_t;

    typedef struct {
        logic [31:0] value;
    } ecc_reg__ECC_SEED__SEED__out_t;

    typedef struct {
        ecc_reg__ECC_SEED__SEED__out_t SEED;
    } ecc_reg__ECC_SEED__out_t;

    typedef struct {
        logic [31:0] value;
    } ecc_reg__ECC_MSG__MSG__out_t;

    typedef struct {
        ecc_reg__ECC_MSG__MSG__out_t MSG;
    } ecc_reg__ECC_MSG__out_t;

    typedef struct {
        logic [31:0] value;
    } ecc_reg__ECC_PRIVKEY__PRIVKEY__out_t;

    typedef struct {
        ecc_reg__ECC_PRIVKEY__PRIVKEY__out_t PRIVKEY;
    } ecc_reg__ECC_PRIVKEY__out_t;

    typedef struct {
        logic [31:0] value;
    } ecc_reg__ECC_PUBKEY_X__PUBKEY_X__out_t;

    typedef struct {
        ecc_reg__ECC_PUBKEY_X__PUBKEY_X__out_t PUBKEY_X;
    } ecc_reg__ECC_PUBKEY_X__out_t;

    typedef struct {
        logic [31:0] value;
    } ecc_reg__ECC_PUBKEY_Y__PUBKEY_Y__out_t;

    typedef struct {
        ecc_reg__ECC_PUBKEY_Y__PUBKEY_Y__out_t PUBKEY_Y;
    } ecc_reg__ECC_PUBKEY_Y__out_t;

    typedef struct {
        logic [31:0] value;
    } ecc_reg__ECC_SIGN_R__SIGN_R__out_t;

    typedef struct {
        ecc_reg__ECC_SIGN_R__SIGN_R__out_t SIGN_R;
    } ecc_reg__ECC_SIGN_R__out_t;

    typedef struct {
        logic [31:0] value;
    } ecc_reg__ECC_SIGN_S__SIGN_S__out_t;

    typedef struct {
        ecc_reg__ECC_SIGN_S__SIGN_S__out_t SIGN_S;
    } ecc_reg__ECC_SIGN_S__out_t;

    typedef struct {
        logic [31:0] value;
    } ecc_reg__ECC_VERIFY_R__VERIFY_R__out_t;

    typedef struct {
        ecc_reg__ECC_VERIFY_R__VERIFY_R__out_t VERIFY_R;
    } ecc_reg__ECC_VERIFY_R__out_t;

    typedef struct {
        logic [31:0] value;
    } ecc_reg__ECC_IV__IV__out_t;

    typedef struct {
        ecc_reg__ECC_IV__IV__out_t IV;
    } ecc_reg__ECC_IV__out_t;

    typedef struct {
        logic intr;
    } ecc_reg__intr_block_t__global_intr_t_agg_sts_dd3dcf0a__out_t;

    typedef struct {
        logic intr;
    } ecc_reg__intr_block_t__global_intr_t_agg_sts_e6399b4a__out_t;

    typedef struct {
        logic intr;
    } ecc_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__out_t;

    typedef struct {
        logic intr;
    } ecc_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__out_t;

    typedef struct {
        ecc_reg__intr_block_t__global_intr_t_agg_sts_dd3dcf0a__out_t error_global_intr_r;
        ecc_reg__intr_block_t__global_intr_t_agg_sts_e6399b4a__out_t notif_global_intr_r;
        ecc_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__out_t error_internal_intr_r;
        ecc_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__out_t notif_internal_intr_r;
    } ecc_reg__intr_block_t__out_t;

    typedef struct {
        ecc_reg__ECC_CTRL__out_t ECC_CTRL;
        ecc_reg__ECC_SCACONFIG__out_t ECC_SCACONFIG;
        ecc_reg__ECC_SEED__out_t ECC_SEED[12];
        ecc_reg__ECC_MSG__out_t ECC_MSG[12];
        ecc_reg__ECC_PRIVKEY__out_t ECC_PRIVKEY[12];
        ecc_reg__ECC_PUBKEY_X__out_t ECC_PUBKEY_X[12];
        ecc_reg__ECC_PUBKEY_Y__out_t ECC_PUBKEY_Y[12];
        ecc_reg__ECC_SIGN_R__out_t ECC_SIGN_R[12];
        ecc_reg__ECC_SIGN_S__out_t ECC_SIGN_S[12];
        ecc_reg__ECC_VERIFY_R__out_t ECC_VERIFY_R[12];
        ecc_reg__ECC_IV__out_t ECC_IV[12];
        ecc_reg__intr_block_t__out_t intr_block_rf;
    } ecc_reg__out_t;

    localparam ECC_REG_ADDR_WIDTH = 32'd12;

endpackage