$UVMF_VIP_LIBRARY_HOME/interface_packages/cptra_status_pkg/src/cptra_status_if.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/cptra_status_pkg/src/cptra_status_monitor_bfm.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/cptra_status_pkg/src/cptra_status_driver_bfm.sv
